In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:85% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:16pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:12pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:12px;}
</style>
"""))

<font size="6" color="red">ch11. 데이터프레임과 시리즈(Pandas)</font>
# 9절. 데이터 그룹화 및 집계

In [276]:
from statsmodels.api import datasets
iris=datasets.get_rdataset('iris').data
iris.iloc[::25]
iris.iloc[[0,49,50,99,100,149]]

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width     Species
0             5.1          3.5           1.4          0.2      setosa
49            5.0          3.3           1.4          0.2      setosa
50            7.0          3.2           4.7          1.4  versicolor
99            5.7          2.8           4.1          1.3  versicolor
100           6.3          3.3           6.0          2.5   virginica
149           5.9          3.0           5.1          1.8   virginica

## 9.1 Group by
    cf. pivot_table

In [277]:
iris.groupby('Species')[['Sepal.Length','Sepal.Width']].sum()

            Sepal.Length  Sepal.Width
Species
setosa             250.3        171.4
versicolor         296.8        138.5
virginica          329.4        148.7

In [ ]:
# 1) 그룹화 방법 1
#    df.groupby(by=[그룹핑 할 열이름])[집계함수 적용해서 출력 할 열들].기초통계함수()
# [함수적용해서 출력할 열들] 생략시 모든 열이 적용

In [278]:
iris.groupby('Species').describe()

           Sepal.Length                                              \
                  count   mean       std  min    25%  50%  75%  max
Species
setosa             50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8
versicolor         50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0
virginica          50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9

           Sepal.Width         ... Petal.Length      Petal.Width         \
                 count   mean  ...          75%  max       count   mean
Species                        ...
setosa            50.0  3.428  ...        1.575  1.9        50.0  0.246
versicolor        50.0  2.770  ...        4.600  5.1        50.0  1.326
virginica         50.0  2.974  ...        5.875  6.9        50.0  2.026


                 std  min  25%  50%  75%  max
Species
setosa      0.105386  0.1  0.2  0.2  0.3  0.6
versicolor  0.197753  1.0  1.2  1.3  1.5  1.8
virginica   0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 32 columns]

In [279]:
iris.groupby('Species').sum()

            Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
Species
setosa             250.3        171.4          73.1         12.3
versicolor         296.8        138.5         213.0         66.3
virginica          329.4        148.7         277.6        101.3

In [280]:
iris_grouped=iris.groupby('Species')
iris_grouped=iris.groupby(iris.Species)
iris_grouped_sum=iris_grouped.sum()
display(iris_grouped_sum)    #iris.groupby('Species').sum()
iris_grouped_sum.loc[['setosa','virginica']]

            Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
Species
setosa             250.3        171.4          73.1         12.3
versicolor         296.8        138.5         213.0         66.3
virginica          329.4        148.7         277.6        101.3

In [281]:
#setosa와virginica 만 집계
iris_grouped_sum.loc[['setosa','virginica']]

           Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
Species
setosa            250.3        171.4          73.1         12.3
virginica         329.4        148.7         277.6        101.3

In [ ]:
print(iris_grouped_sum.index)

In [ ]:
iris_grouped_sum.reset_index(inplace=True) #인덱스를 컬럼으로 편입시킴

In [ ]:
iris_grouped_sum

In [ ]:
iris_grouped_sum[(iris_grouped_sum.Species=='setosa')|(iris_grouped_sum.Species=='virginica')]
iris_grouped_sum[iris_grouped_sum.Species.isin(['setosa','virginica'])]

In [ ]:
# 1) 그룹화 방법 1-1 :그룹핑할 때 index를 컬럼 데이터로 편입(reset_index()가 필요 x)
#    df.groupby(by=[그룹핑 할 열이름], as_index=False)[집계함수 적용해서 출력 할 열들].기초통계함수()
# [함수적용해서 출력할 열들] 생략시 모든 열이 적용
iris.groupby('Species',as_index=False).sum()
iris.groupby(iris['Species'],as_index=False).sum()
iris.groupby(iris.Species,as_index=False).sum()

In [ ]:
#종별 Sepal.Length 와 Sepal.Width 의 평균
iris.groupby('Species').mean()[['Sepal.Length','Sepal.Width']]
iris.groupby('Species')[['Sepal.Length','Sepal.Width']].mean()

In [ ]:
#종별 sepal.length의 합계

In [ ]:
iris.groupby('Species')[['Sepal.Length']].sum()

In [ ]:
iris.groupby('Species')['Sepal.Length',].sum()

In [ ]:
#그룹화방법1
#df.groupby(by=[그룹핑할열이름들], as_index=T/F)[함수적용해서출력할열들].함수명()
#그룹화방법2
#df.pivot_table(index='그룹핑할열이름또는이름들',
#               values='함수적용해서출력할열들', 
#               aggfunc=함수명(기본값:mean)
#               )
#pd.pivot_table(df,index,values,aggfunc) 로도 쓸수 있다


g= iris.pivot_table(index='Species',
                #values
                #aggfunc='sum'       
                )
import matplotlib.pyplot as plt
#범례를 밖으로 : 시각화20page. 판다스 60page.
g.plot(kind='bar',figsize=(10,3), rot=0)
plt.legend(bbox_to_anchor=(1.05, 1), loc=2, borderaxespad=0.)
plt.show()

In [ ]:
iris.groupby('Species').mean()

In [ ]:
iris.pivot_table(index='Species', values='Sepal.Length', aggfunc='count')
iris.groupby('Species')[['Sepal.Length']].count()  #정렬이 안됨
iris['Species'].value_counts() #정렬까지

In [ ]:
#임의로 각 열마다 결측치를 할당(0번째열은 결측치1 / 1번째열은 결측치2 / 2번째열은 결측치3 / 3번째열은 결측치4)

In [ ]:
import numpy as np
import random
random.sample(range(0,150),3)
for col in range(iris.shape[1]-1):
    rows=random.sample(range(len(iris)),col+1)
    iris.iloc[rows,col] = np.nan

In [ ]:
iris.isna().sum()

In [ ]:
#열별 결측치를 제외한 데이터 갯수
iris.count()

In [ ]:
iris.groupby('Species').count()
iris.pivot_table(index='Species',aggfunc='count')

In [ ]:
iris.head(1)

In [ ]:
#iris로 다중열 그룹화 하기위해 데이터 추가
#iris 행수는 150개 = Species 3그룹, num 6그룹
np.array([[i]*25 for i in range(6)]).flatten()

In [ ]:
iris['Num']=np.array([[i]*25 for i in range(6)]).flatten()
iris.iloc[::25]

In [ ]:
#import pandas as pd
#pd.options.display.max_rows=150
#iris                                  전체열 다 확인하기 위함

In [ ]:
#종별, num별 합계 
result=iris.groupby(['Species','Num']).sum()

In [ ]:
result.index

In [ ]:
result.loc[['setosa','virginica']]

In [ ]:
result.loc[[('setosa',0),('virginica',5)]]

In [ ]:
#종별,num별 합계
iris.pivot_table(index=['Species','Num'])

In [ ]:
#종별 기초 통계량들 다 출력
iris.groupby(['Species']).describe().T

## 9.2 그룹간 데이터 처리

In [ ]:
from statsmodels.api import datasets
iris=datasets.get_rdataset('iris').data
iris.head(3)

In [ ]:
iris_grouped=iris.groupby('Species')
list(iris_grouped)

In [ ]:
#종별 상위 5행 출력
for speciesname, group in iris_grouped :
    print(speciesname)
    display(group.head(5))

In [ ]:
#종별 샘플링 출력
for speciesname, group in iris_grouped :
    print(speciesname)
    display(group.sample(3).sort_index())#.reset_index(drop=True)) 인덱스 새로 부여

In [ ]:
#종별 0,15,30,45
for speciesname, group in iris_grouped :
    print(speciesname)
    display(group.iloc[[0,15,30,45]])

## 9.3 데이터프레임 그룹별 인덱싱

In [ ]:
#위와 100%같이 출력
# for speciesname, group in iris_grouped :
#     print(speciesname)
#     display(group.iloc[[0,15,30,45]])
r=iris.groupby('Species').take([0,15,30,45])
r

In [ ]:
r.loc['versicolor']

# 10절. 데이터 구조 변경
- 와이드포맷 <---> 롱포맷(tidy data)                 ※ 와이드포맷은 시각화에 최적화!
- 판다스 공식문서에 나오는 melt : https://pandas.pydata.org/docs/user_guide/reshaping.html#melt-and-wide-to-long
- Tidy data : https://vita.had.co.nz/papers/tidy-data.pdf

In [ ]:
from statsmodels.api import datasets
airquality = datasets.get_rdataset('airquality').data #1973년 뉴욕 공기 질 데이터셋
airquality.head()

## 10.1 melt를 이용한 언피벗팅(와이드포맷→롱포맷)
- df.melt(id_vars, value_vars, vars_name,_ value_name)
- pd.melt(df,id_vars, value_vars, vars_name,_ value_name)

In [ ]:
import pandas as pd
airquality_melted=airquality.melt(id_vars=['Month','Day'])
pd.melt(airquality,id_vars=['Month','Day'],
        #value_vars=['Ozone','Solar.R','Wind','Temp']) melt될 열이름 (안쓰면 모두 melt)
        )

In [ ]:
airquality_melted = airquality.melt(id_vars=['Month','Day'],
                                   var_name='변수명', #melt된 데이터의 열이름
                                    value_name='값'  #데이터가된 열이름
                                   )
airquality_melted=airquality_melted.sort_values(by=['Month','Day']).reset_index(drop=True)
airquality_melted

## 10.2 pivot_table을 이용한 피벗팅(롱포맷 → 와이드포맷)
- df.pivot_table(index, columns, values)
- pd.pivot_table(df, index, columns, values)

In [ ]:
airquality2 = airquality_melted.pivot_table(index=['Month','Day'], columns='변수명',)#values='값')
airquality2.columns=airquality2.columns.droplevel(level=0)
airquality2.columns.name=None
airquality2= airquality2.reset_index()
airquality2

In [ ]:
airquality_melted.pivot_table(index=['Month','Day'], columns='변수명',values='값').reset_index()

# 11절. 데이터프레임에 함수 적용시키기
- apply(func, axis=0) :데이터프레임이나 시리즈 모두 적용가능    #axis=0 1행부터 끝행까지
- map(func) : 각 요소별로 func 적용(1차원 시리즈에서만 가능)
- applymap(func) : 각 요소별로 func적용(데이터프레임에서만 가능)

## 11.1 apply / map

In [ ]:
# ex1. 1차원 시리즈에 apply/map 이용
member = pd.read_csv('data/ch11_member.csv',comment='#')
member.info()

In [ ]:
def get_year(datestr) :
    return int(datestr.split('-')[0])
get_year = lambda datestr : int(datestr.split('-')[0])
get_year('1991-01-01')

In [ ]:
member['년']=member['Birth'].map(lambda datestr : int(datestr.split('-')[0]))
member

In [ ]:
def get_month(datestr) :
    return int(datestr.split('-')[1])

get_month= lambda datestr : int(datestr.split('-')[1])
get_month('1991-01-01')

In [ ]:
member['년']=member['Birth'].map(lambda datestr : int(datestr.split('-')[0]))
member['월']=member['Birth'].apply(lambda datestr : int(datestr.split('-')[1]))
member

In [ ]:
#ex2 2차원 데이터프레임에서 apply(func, axis=1)
%ls C:\ai\downloads\shareData\분양가격

In [11]:
df_last =pd.read_csv('c:/ai/downloads/shareData/분양가격/주택도시보증공사_전국 신규 민간아파트 분양가격 동향_20260531 (3).csv',
                    encoding='cp949')
df_last.head(5)

  지역명                     규모구분    연도   월 분양가격(제곱미터당 천원)
0  서울                     모든면적  2015  10           5841
1  서울            전용면적 60제곱미터이하  2015  10           5652
2  서울   전용면적 60제곱미터초과 85제곱미터이하  2015  10           5882
3  서울  전용면적 85제곱미터초과 102제곱미터이하  2015  10           5721
4  서울           전용면적 102제곱미터초과  2015  10           5879

In [12]:
def year_month(series):
    return '{}-{:02}'.format(series['연도'],series['월']) 
year_month(df_last.loc[0])

'2015-10'

In [13]:
df_last['연도월']=df_last.apply(lambda series :'{}-{:02}'.format(series['연도'],series['월']),axis=1 )
df_last.tail()

      지역명                     규모구분    연도  월 분양가격(제곱미터당 천원)      연도월
10875  제주                     모든면적  2026  5           4473  2026-05
10876  제주            전용면적 60제곱미터이하  2026  5            NaN  2026-05
10877  제주   전용면적 60제곱미터초과 85제곱미터이하  2026  5           4485  2026-05
10878  제주  전용면적 85제곱미터초과 102제곱미터이하  2026  5            NaN  2026-05
10879  제주           전용면적 102제곱미터초과  2026  5           4350  2026-05

In [14]:
#ex3 iris apply(func, axis=1)

In [15]:
iris.head(1)

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa

In [16]:
import numpy as np
X=iris.iloc[:,:-1]
avg=np.mean(iris.iloc[:,:-1],axis=0) #열별 평균
avg=iris.iloc[:,:-1].mean(axis=0)
avg

Sepal.Length    5.843333
Sepal.Width     3.057333
Petal.Length    3.758000
Petal.Width     1.199333
dtype: float64

In [17]:
# 각 열별 평균과의 거리를 출력
X.apply(lambda x : round(x-avg,2), axis=1)

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
0           -0.74         0.44         -2.36         -1.0
1           -0.94        -0.06         -2.36         -1.0
2           -1.14         0.14         -2.46         -1.0
3           -1.24         0.04         -2.26         -1.0
4           -0.84         0.54         -2.36         -1.0
..            ...          ...           ...          ...
145          0.86        -0.06          1.44          1.1
146          0.46        -0.56          1.24          0.7
147          0.66        -0.06          1.44          0.8
148          0.36         0.34          1.64          1.1
149          0.06        -0.06          1.34          0.6

[150 rows x 4 columns]

## 11.2 applymap

In [18]:
X.applymap(lambda x : np.round(x,3))  # applymap 은 반드시 데이타프레임에서만 쓸수 있다

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

※ melt() 및 함수 적용시키기 연습예제(분양가격 csv 두파일 통합)
- 와이드포맷 → 롱포맷(melt) : 2013~2015년데이터
- 평당분양가격/3.3 => 분양가격(제곱미터당 천원)
- 2013년 12월 -> 2013과 12를 나눠 '연도'와 '월'컬럼(apply,map)
  =>new_first 편집됨
- df_last['규모구분'] =='모든면적' 데이터만 추출(지역, 연도, 월, 분양가격(제곱미터당 천원) 컬럼만 추출
- df_last의 지역명 칼럼명을 지역으로 변경
  =>new_last
- pd.concat([new_first,new_last])

In [19]:
import pandas as pd
df_first =pd.read_csv('c:/ai/downloads/shareData/분양가격/전국 평균 평당 분양가격(2013년 9월부터 2015년 8월까지).csv',
                    encoding='cp949')
df_first.head(1)

,지역,2013년12월,2014년1월,2014년2월,2014년3월,2014년4월,2014년5월,2014년6월,2014년7월,2014년8월,...,2014년11월,2014년12월,2015년1월,2015년2월,2015년3월,2015년4월,2015년5월,2015년6월,2015년7월,2015년8월
0,서울,18189,17925,17925,18016,18098,19446,18867,18742,19274,...,20242,20269,20670,20670,19415,18842,18367,18374,18152,18443

In [20]:
#와이드포맷 -> 롱포맷
new_first=df_first.melt(id_vars='지역',var_name='연도월',value_name='평당분양가격')

In [21]:
df_last.head(1)

  지역명  규모구분    연도   월 분양가격(제곱미터당 천원)      연도월
0  서울  모든면적  2015  10           5841  2015-10

In [22]:
#평당분양가격/3.3 => 제곱미터당 분양가격
new_first['분양가격(제곱미터당 천원)']=new_first['평당분양가격']/3.3

In [23]:
new_first.head(1)

   지역       연도월  평당분양가격  분양가격(제곱미터당 천원)
0  서울  2013년12월   18189     5511.818182

In [24]:
# - 2013년 12월 -> 2013과 12를 나눠 '연도'와 '월'컬럼(apply,map)
def parse_year(datestr):
    return int(datestr.split('년')[0])
parse_year("2013년12월")
#(lambda datestr : int(datestr.split('년')[0]))("2013년12월")

def parse_month(datestr):
    return int(datestr.split('년')[1][:-1])
parse_month("2013년12월")
#(lambda datestr : int(datestr.split('년')[1][:-1])

12

In [25]:
new_first['연도월'].map(lambda datestr : int(datestr.split('년')[0]))

0      2013
1      2013
2      2013
3      2013
4      2013
       ...
352    2015
353    2015
354    2015
355    2015
356    2015
Name: 연도월, Length: 357, dtype: int64

In [26]:
new_first['연도']=new_first['연도월'].map(lambda datestr : int(datestr.split('년')[0]))
new_first['월']=new_first['연도월'].apply(lambda datestr : int(datestr.split('년')[1][:-1]))
new_first=new_first.drop(['연도월','평당분양가격'],axis=1)
new_first.head()

   지역  분양가격(제곱미터당 천원)    연도   월
0  서울     5511.818182  2013  12
1  부산     2457.878788  2013  12
2  대구     2448.484848  2013  12
3  인천     3092.121212  2013  12
4  광주     1847.878788  2013  12

In [36]:
# - df_last['규모구분'] =='모든면적' 데이터만 추출(지역, 연도, 월, 분양가격(제곱미터당 천원) 컬럼만 추출
new_last=df_last.loc[df_last['규모구분']=='모든면적',['지역명','연도','월','분양가격(제곱미터당 천원)']]
#new_last.columns =['지역','연도','월','분양가격(제곱미터당 천원)'] column이 작을때만 사용
new_last.rename(columns={'지역명':'지역'},inplace=True) #지역명 컬럼명을 지역으로 변경
new_last.head()

    지역    연도   월 분양가격(제곱미터당 천원)
0   서울  2015  10           5841
5   인천  2015  10           3163
10  경기  2015  10           3138
15  부산  2015  10           3112
20  대구  2015  10           2682

In [ ]:
# - pd.concat([new_first,new_last])

In [42]:
df = pd.concat([new_first,new_last]#,axis=0
              ).reset_index(drop=True) # 같은 컬럼명 기준으로 행 연결
df

      지역 분양가격(제곱미터당 천원)    연도   월
0     서울    5511.818182  2013  12
1     부산    2457.878788  2013  12
2     대구    2448.484848  2013  12
3     인천    3092.121212  2013  12
4     광주    1847.878788  2013  12
...   ..            ...   ...  ..
2528  전북           3853  2026   5
2529  전남           3785  2026   5
2530  경북           4106  2026   5
2531  경남           4682  2026   5
2532  제주           4473  2026   5

[2533 rows x 4 columns]

In [45]:
df.loc[df['연도']==2013].head(1)

   지역 분양가격(제곱미터당 천원)    연도   월
0  서울    5511.818182  2013  12

# 12절. 일괄변경하기(결측치나 특정값)
## 12.1 fillna(결측치를 어떤 값으로 대체)
- 대부분의 결측치는 drop하거나, 평균값대체, 중위수(중앙값==2사분위수)대체, 최빈값대체, 이전값, 다음값, 그룹별 평균값으로 대체

In [46]:
from sklearn import datasets

In [48]:
df = pd.DataFrame([[np.nan,2,np.nan,0],
                   [3,     4,np.nan,1],
                   [np.nan,3,np.nan,5],
                   [np.nan,3,np.nan,4]],columns=['a', 'b', 'c','d' ])
df

     a  b   c  d
0  NaN  2 NaN  0
1  3.0  4 NaN  1
2  NaN  3 NaN  5
3  NaN  3 NaN  4

In [ ]:
#모든 결측치를 무조건 0으로 대체

In [49]:
df.fillna(0)

     a  b    c  d
0  0.0  2  0.0  0
1  3.0  4  0.0  1
2  0.0  3  0.0  5
3  0.0  3  0.0  4

In [52]:
#결측치를 이전행의 값으로 대체
df.fillna(method='ffill')

     a  b   c  d
0  NaN  2 NaN  0
1  3.0  4 NaN  1
2  3.0  3 NaN  5
3  3.0  3 NaN  4

In [53]:
#결측치를 다음행의 값으로 대체
df.fillna(method='bfill')

     a  b   c  d
0  3.0  2 NaN  0
1  3.0  4 NaN  1
2  NaN  3 NaN  5
3  NaN  3 NaN  4

In [55]:
#결측치를 열마다 특정값으로 대체
values = {'a':99,'b':98, 'c':97,'d':96}
df.fillna(value=values)

      a  b     c  d
0  99.0  2  97.0  0
1   3.0  4  97.0  1
2  99.0  3  97.0  5
3  99.0  3  97.0  4

In [58]:
#결측치를 각 열의 평균값(중위값,최빈값)으로 대체
df.fillna(value=df.mean(axis=0))

     a  b   c  d
0  3.0  2 NaN  0
1  3.0  4 NaN  1
2  3.0  3 NaN  5
3  3.0  3 NaN  4

In [60]:
#결측치를 각 열의 평균값으로 대체(결측치 대체는 2번째까지만)
df.fillna(value=df.mean(axis=0),limit=2)

     a  b   c  d
0  3.0  2 NaN  0
1  3.0  4 NaN  1
2  3.0  3 NaN  5
3  NaN  3 NaN  4

In [61]:
#결측치를 각 열의 중위값으로 대체
df.fillna(value=df.median(axis=0))

     a  b   c  d
0  3.0  2 NaN  0
1  3.0  4 NaN  1
2  3.0  3 NaN  5
3  3.0  3 NaN  4

In [66]:
#결측치를 각 열의 최빈값으로 대체
df.fillna(df.mode().loc[0])

     a  b   c  d
0  3.0  2 NaN  0
1  3.0  4 NaN  1
2  3.0  3 NaN  5
3  3.0  3 NaN  4

## 12.2 replace(to_value,new_value,inplace=T/F)
- to_value를 new_value로 변경
- to_value에는 정규표현식 이용 가능

In [74]:
s = pd.Series([0, 1, 2, 3, None])
s.replace(np.nan,0,inplace=True)
s
s.replace([0,1],99) # 0이나1을 99로 변경
s.replace([0,1,2],[100,101,102])

0    100.0
1    101.0
2    102.0
3      3.0
4    100.0
dtype: float64

In [77]:
df=pd.DataFrame({'a':['bat','foo', 'bait'], 'b':['abc','bar','xyz']})
df

      a    b
0   bat  abc
1   foo  bar
2  bait  xyz

In [83]:
df.replace('ba.+','xx',regex=True)
df.replace('ba.+$','xx',regex=True)
df.replace(regex=['ba.+','fo'],value='XX')

     a    b
0   XX  abc
1  XXo   XX
2   XX  xyz

In [84]:
df.replace({'a':'bat','b':'abc'},'XX')

      a    b
0    XX   XX
1   foo  bar
2  bait  xyz

## 12.3 where(조건), mask(조건)

In [86]:
a=np.array([1,2,3,4,5,6])
np.where(a>3)

(array([3, 4, 5], dtype=int64),)

In [88]:
s=pd.Series(range(10,20))
#15이상 
s[s>=15]

5    15
6    16
7    17
8    18
9    19
dtype: int64

In [89]:
s.where(s>=15) #조건이 만조되는 데이터는 그대로 출력, 만족되니 않는 데이터는 결측지

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
5    15.0
6    16.0
7    17.0
8    18.0
9    19.0
dtype: float64

In [90]:
s.where(s>=15,other=-1) #조건이 만조되는 데이터는 그대로 출력, 만족되니 않는 데이터는 -1

0    -1
1    -1
2    -1
3    -1
4    -1
5    15
6    16
7    17
8    18
9    19
dtype: int64

In [91]:
s.mask(s>=15) #조건이 만족되는 데이터만 결측치

0    10.0
1    11.0
2    12.0
3    13.0
4    14.0
5     NaN
6     NaN
7     NaN
8     NaN
9     NaN
dtype: float64

## 12.4 dropna
- 결측치가 있는 데이터 누락(행기준, 열기준)

In [93]:
df=pd.DataFrame({'name':['홍','김',np.nan,np.nan],
                'age':[np.nan, 20, 30, np.nan],
                'born':['서울','부산',np.nan,np.nan]})
df

  name   age born
0    홍   NaN   서울
1    김  20.0   부산
2  NaN  30.0  NaN
3  NaN   NaN  NaN

In [97]:
df.dropna(axis=0) #결측치가 하나라도 있는 행을 drop , inplace=True가 아니면 return

  name   age born
1    김  20.0   부산

In [99]:
df.dropna(thresh=2)#결측치가 아닌값이 2개이상이면 drop안 함

  name   age born
0    홍   NaN   서울
1    김  20.0   부산

In [101]:
df.dropna(subset=['name','age'])#name열과 age열에 결측치가 하나라도 있는 행 drop

  name   age born
1    김  20.0   부산

In [ ]:
df.dropna(how='all') #모두 결측치인 행 drop

In [102]:
df.dropna(axis=1) #결측치가 하나라도 있는 열은 열을 drop

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [103]:
df.dropna(how='all',axis=1) #결측치가 하나라도 있는 열은 열을 drop

  name   age born
0    홍   NaN   서울
1    김  20.0   부산
2  NaN  30.0  NaN
3  NaN   NaN  NaN

### ※ iris 결측치를 열별 평균으로 대체(교안 80p : fillna)

In [104]:
iris.head(10)

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

 ### ※ iris 결측치를 종별, 열별 평균으로 대체(apply적용)

In [106]:
iris.isna().sum() #iris.isnull().sum()

Sepal.Length    0
Sepal.Width     0
Petal.Length    0
Petal.Width     0
Species         0
dtype: int64

In [107]:
iris.notna() # 열마다 결측치를 제외한 데이터 갯수

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
0            True         True          True         True     True
1            True         True          True         True     True
2            True         True          True         True     True
3            True         True          True         True     True
4            True         True          True         True     True
..            ...          ...           ...          ...      ...
145          True         True          True         True     True
146          True         True          True         True     True
147          True         True          True         True     True
148          True         True          True         True     True
149          True         True          True         True     True

[150 rows x 5 columns]

In [113]:
# 1단계 : iris 데이터에서 결측치를 인위적으로 random하게 열 마다 20씩 결측치를 할당한다
import random
print(random.sample(range(iris.shape[0]),20))

[71, 13, 41, 138, 86, 146, 12, 56, 144, 106, 88, 149, 4, 139, 82, 89, 36, 18, 147, 113]

In [115]:
for col in range(iris.shape[1]-1):
    randomidx=random.sample(range(iris.shape[0]),20)
    #print(randomidx,col)
    iris.iloc[randomidx,col] =np.nan

In [118]:
iris.isna().sum()

Sepal.Length    20
Sepal.Width     20
Petal.Length    20
Petal.Width     20
Species          0
dtype: int64

In [123]:
iris[iris['Sepal.Length'].isna() | iris['Sepal.Width'].isna() | iris['Sepal.Length'].isnull() | iris['Sepal.Width'].isnull()]

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width     Species
3             NaN          NaN           1.5          0.2      setosa
15            5.7          NaN           1.5          0.4      setosa
19            5.1          NaN           NaN          0.3      setosa
20            5.4          NaN           1.7          0.2      setosa
21            NaN          3.7           1.5          0.4      setosa
24            NaN          3.4           1.9          0.2      setosa
47            4.6          NaN           1.4          0.2      setosa
51            6.4          NaN           NaN          1.5  versicolor
56            NaN          3.3           4.7          NaN  versicolor
59            NaN          2.7           3.9          1.4  versicolor
61            NaN          3.0           4.2          1.5  versicolor
64            5.6          NaN           3.6          1.3  versicolor
67            NaN          2.7           4.1          1.0  versicolor
70            5.9          NaN           4.8          1.8  versicolor
74            NaN          NaN           4.3          1.3  versicolor
75            NaN          NaN           4.4          1.4  versicolor
78            NaN          2.9           4.5          1.5  versicolor
82            5.8          NaN           NaN          1.2  versicolor
83            NaN          2.7           5.1          NaN  versicolor
85            NaN          3.4           NaN          NaN  versicolor
88            NaN          3.0           4.1          NaN  versicolor
92            NaN          2.6           4.0          1.2  versicolor
93            5.0          NaN           3.3          1.0  versicolor
98            NaN          2.5           NaN          NaN  versicolor
109           NaN          NaN           6.1          2.5   virginica
111           6.4          NaN           5.3          1.9   virginica
116           6.5          NaN           5.5          1.8   virginica
120           NaN          3.2           5.7          2.3   virginica
128           NaN          2.8           5.6          2.1   virginica
132           6.4          NaN           5.6          2.2   virginica
136           6.3          NaN           5.6          NaN   virginica
137           NaN          3.1           5.5          1.8   virginica
139           6.9          NaN           5.4          2.1   virginica
143           6.8          NaN           5.9          2.3   virginica
148           6.2          NaN           5.4          2.3   virginica
149           NaN          3.0           5.1          1.8   virginica

In [132]:
#3단계 : 결측치를 열평균으로 대체된 iris데이터를 출력한다.
iris.iloc[:,:-1].mean(axis=0)
iris.mean(axis=0,numeric_only=True) # 열평균
iris_fillna=iris.fillna(value=iris.iloc[:,:-1].mean(axis=0))
iris_fillna.isna().sum()

Sepal.Length    0
Sepal.Width     0
Petal.Length    0
Petal.Width     0
Species         0
dtype: int64

In [137]:
iris_fillna.iloc[:,:-1]= iris_fillna.iloc[:,:-1].applymap(lambda x : np.round(x, 3))
iris_fillna

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0           5.100        3.500         1.400          0.2     setosa
1           4.900        3.000         1.400          0.2     setosa
2           4.700        3.200         1.300          0.2     setosa
3           5.835        3.041         1.500          0.2     setosa
4           5.000        3.600         1.400          0.2     setosa
..            ...          ...           ...          ...        ...
145         6.700        3.000         5.200          2.3  virginica
146         6.300        2.500         3.737          1.9  virginica
147         6.500        3.000         5.200          2.0  virginica
148         6.200        3.041         5.400          2.3  virginica
149         5.835        3.000         5.100          1.8  virginica

[150 rows x 5 columns]

In [138]:
iris_fillna.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sepal.Length  150 non-null    float64
 1   Sepal.Width   150 non-null    float64
 2   Petal.Length  150 non-null    float64
 3   Petal.Width   150 non-null    float64
 4   Species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [ ]:
 ### ※ iris 결측치를 종별, 열별 평균으로 대체(apply적용)

In [144]:
iris_mean=iris.groupby(by=['Species']).mean()
iris_mean

            Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
Species
setosa          5.017021     3.411111      1.473333     0.253333
versicolor      5.950000     2.751163      4.232500     1.302439
virginica       6.591111     2.940476      5.560000     2.002273

In [146]:
iris.fillna(value=iris_mean) # 결측치 대체 안됨

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             NaN          NaN           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           NaN          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          NaN           5.4          2.3  virginica
149           NaN          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [182]:
#np.isnan(스칼라값) :nan만 결측치로 인식, 결측치인지 여부(값이 숫자형이어야 함)
#pd.isna(스칼라값), pd.isnull(스칼라값): nan과 None을 모두 결측치로 인식하고 결측치인지 여부(값이 숫자형이 아니어도 됨)
def fillna_grouped_mean(row):
    row =row.copy()
    for col, item in row.items():
        #print(col, item, row[col])
        #item이 결측치이면 해당 species를 가져와서 대체할 결측치 iris_mean.loc[종이름,col]로 대체
        #if col!='Species' and np.isnan(item): #결측치인지 여부
        if pd.isna(item):    
            Species = row['Species']
            row[col] = iris_mean.loc[Species,col] # 종별 열별 평균값으로 대체
    return row
fillna_grouped_mean(iris.iloc[3])

Sepal.Length    5.017021
Sepal.Width     3.411111
Petal.Length         1.5
Petal.Width          0.2
Species           setosa
Name: 3, dtype: object

In [183]:
iris.apply(fillna_grouped_mean,axis=1)

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0        5.100000     3.500000          1.40          0.2     setosa
1        4.900000     3.000000          1.40          0.2     setosa
2        4.700000     3.200000          1.30          0.2     setosa
3        5.017021     3.411111          1.50          0.2     setosa
4        5.000000     3.600000          1.40          0.2     setosa
..            ...          ...           ...          ...        ...
145      6.700000     3.000000          5.20          2.3  virginica
146      6.300000     2.500000          5.56          1.9  virginica
147      6.500000     3.000000          5.20          2.0  virginica
148      6.200000     2.940476          5.40          2.3  virginica
149      6.591111     3.000000          5.10          1.8  virginica

[150 rows x 5 columns]

# 13절. 시리즈
- 1차원 데이터

In [184]:
s= pd.Series([1000,7000,5000], index=['banana','mango','apple'])
s

banana    1000
mango     7000
apple     5000
dtype: int64

In [188]:
s['banana'], s.banana

(1000, 1000)

In [189]:
s['banana':'apple']

banana    1000
mango     7000
apple     5000
dtype: int64

In [196]:
s['watermelon']=20000

In [197]:
s.drop('watermelon',inplace=True)

In [198]:
s

banana    1000
mango     7000
apple     5000
dtype: int64

In [199]:
s.sort_index()

apple     5000
banana    1000
mango     7000
dtype: int64

In [200]:
s.sort_values() #값에 의한 정렬(기본은 ascending=True 오름차순)

banana    1000
apple     5000
mango     7000
dtype: int64

In [201]:
s.sort_values(ascending=False)

mango     7000
apple     5000
banana    1000
dtype: int64

In [202]:
s.to_frame(name='price') #열이름을 지정하여 데이터프레임으로 전환

           0
banana  1000
mango   7000
apple   5000

In [203]:
s.to_frame(name='price').T

       banana  mango  apple
price    1000   7000   5000

# 14절. 연습문제

In [302]:
import seaborn as sns
iris = sns.load_dataset("iris")
type(iris)

pandas.core.frame.DataFrame

In [303]:
# 연습문제1  iris 데이터에서 처음 다섯개 행만 출력하세요
iris.head(5)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [304]:
# 연습문제2 iris 데이터를데이터프레임 변수인 독립변수 X와 종속변수 y로 나누세요. 종속변수는 species 열입니다.
x=iris.iloc[...,:-1]
y=iris.iloc[...,-1:]

In [305]:
x=iris.loc[...,:'petal_width']
y=iris.loc[...,'species':]

In [335]:
# 연습문제3 iris 데이터에서 처음 50개행을 빼내서 temp변수에 저장하세요
temp=iris.head(50)
temp1=iris[:50]
temp2=iris.loc[:49]
temp3=iris.iloc[:50]

SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (256794793.py, line 6)

In [336]:
# 연습문제4 3번에서 선택한 데이터프레임의 요약정보를 출력하세요. 모든 열에 대해 요약정보가 출력되어야 합니다.
temp.describe(include='all') #include='all' 생략하면 안됨

        sepal_length  sepal_width  petal_length  petal_width species
count       50.00000    50.000000     50.000000    50.000000      50
unique           NaN          NaN           NaN          NaN       1
top              NaN          NaN           NaN          NaN  setosa
freq             NaN          NaN           NaN          NaN      50
mean         5.00600     3.428000      1.462000     0.246000     NaN
std          0.35249     0.379064      0.173664     0.105386     NaN
min          4.30000     2.300000      1.000000     0.100000     NaN
25%          4.80000     3.200000      1.400000     0.200000     NaN
50%          5.00000     3.400000      1.500000     0.200000     NaN
75%          5.20000     3.675000      1.575000     0.300000     NaN
max          5.80000     4.400000      1.900000     0.600000     NaN

In [308]:
# 연습문제5 versicolor종의 데이터만 iris_versicolor변수에 저장하세요
iris_versicolor=iris.loc[iris['species']=='versicolor']

In [309]:
# 연습문제6 2번의 X와 y변수를 합해서 iris_df데이터 프레임으로 만드세요
iris_df=pd.concat((x,y),axis=1)

In [310]:
# 연습문제7 iris 데이터의 각 열 평균값을 출력하세요
iris.mean(axis=0,numeric_only=True)

sepal_length    5.843333
sepal_width     3.057333
petal_length    3.758000
petal_width     1.199333
dtype: float64

In [311]:
# 연습문제8 데이터의 각 열들 사이의 상관계수를 출력하세요
iris.corr(numeric_only=True)

              sepal_length  sepal_width  petal_length  petal_width
sepal_length      1.000000    -0.117570      0.871754     0.817941
sepal_width      -0.117570     1.000000     -0.428440    -0.366126
petal_length      0.871754    -0.428440      1.000000     0.962865
petal_width       0.817941    -0.366126      0.962865     1.000000

In [312]:
# 연습문제9 iris 데이터에서 각 요소들과 변수별 평균과 차이를 출력하세요 다음 그림은 처음 다섯개행의 출력결과 입니다.
import numpy as np
X=iris.iloc[:,:-1]
avg=iris.mean(axis=0,numeric_only=True)
X.apply(lambda x : x-avg, axis=1).head(5)

   sepal_length  sepal_width  petal_length  petal_width
0     -0.743333     0.442667        -2.358    -0.999333
1     -0.943333    -0.057333        -2.358    -0.999333
2     -1.143333     0.142667        -2.458    -0.999333
3     -1.243333     0.042667        -2.258    -0.999333
4     -0.843333     0.542667        -2.358    -0.999333

In [313]:
# 연습문제10 iris 데이터의 종별 평균을 출력하세요
iris.groupby('species').mean()

            sepal_length  sepal_width  petal_length  petal_width
species
setosa             5.006        3.428         1.462        0.246
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

In [314]:
iris.pivot_table(index='species',aggfunc='mean',sort=False)

            sepal_length  sepal_width  petal_length  petal_width
species
setosa             5.006        3.428         1.462        0.246
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

In [337]:
# 연습문제 11  iris 데이터에서 각 요소들과 종별 변수의 평균과의 차이를 출력하세요.
# 각 종별로 3개씩 출력하세요.

            sepal_length  sepal_width  petal_length  petal_width
0                    NaN          NaN           NaN          NaN
1                    NaN          NaN           NaN          NaN
2                    NaN          NaN           NaN          NaN
3                    NaN          NaN           NaN          NaN
4                    NaN          NaN           NaN          NaN
...                  ...          ...           ...          ...
148                  NaN          NaN           NaN          NaN
149                  NaN          NaN           NaN          NaN
setosa               NaN          NaN           NaN          NaN
versicolor           NaN          NaN           NaN          NaN
virginica            NaN          NaN           NaN          NaN

[153 rows x 4 columns]

In [338]:
mean_by_species = iris.groupby('species').mean()
mean_by_species

            sepal_length  sepal_width  petal_length  petal_width
species
setosa             5.006        3.428         1.462        0.246
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

In [339]:
result = iris.apply(lambda series : 
           series - mean_by_species.loc[series.species], axis=1)
result.head()

   petal_length  petal_width  sepal_length  sepal_width  species
0        -0.062       -0.046         0.094        0.072      NaN
1        -0.062       -0.046        -0.106       -0.428      NaN
2        -0.162       -0.046        -0.306       -0.228      NaN
3         0.038       -0.046        -0.406       -0.328      NaN
4        -0.062       -0.046        -0.006        0.172      NaN

In [341]:
iris.apply(lambda row : row - mean_by_species.loc[row.species], axis=1)

     petal_length  petal_width  sepal_length  sepal_width  species
0          -0.062       -0.046         0.094        0.072      NaN
1          -0.062       -0.046        -0.106       -0.428      NaN
2          -0.162       -0.046        -0.306       -0.228      NaN
3           0.038       -0.046        -0.406       -0.328      NaN
4          -0.062       -0.046        -0.006        0.172      NaN
..            ...          ...           ...          ...      ...
145        -0.352        0.274         0.112        0.026      NaN
146        -0.552       -0.126        -0.288       -0.474      NaN
147        -0.352       -0.026        -0.088        0.026      NaN
148        -0.152        0.274        -0.388        0.426      NaN
149        -0.452       -0.226        -0.688        0.026      NaN

[150 rows x 5 columns]

In [340]:
result = result.groupby(iris.species).head(3)
result

     petal_length  petal_width  sepal_length  sepal_width  species
0          -0.062       -0.046         0.094        0.072      NaN
1          -0.062       -0.046        -0.106       -0.428      NaN
2          -0.162       -0.046        -0.306       -0.228      NaN
50          0.440        0.074         1.064        0.430      NaN
51          0.240        0.174         0.464        0.430      NaN
52          0.640        0.174         0.964        0.330      NaN
100         0.448        0.474        -0.288        0.326      NaN
101        -0.452       -0.126        -0.788       -0.274      NaN
102         0.348        0.074         0.512        0.026      NaN