In [2]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:90% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:20pt;}
.inner_cell{font-size:20pt;}
div.text_cell_render pre code {font-size:20pt; line-height:30px;}
div.output {font-size:20pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:10pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:20pt;padding:5px;}
table.dataframe{font-size:20px;}
</style>
"""))

<font color ='red' size='6'><b>ch14. 웹 데이터 수집</b></font>

# 1절. BeautifulSoup과 parser
    (정적 웹크롤링, 공공api사용)
`pip install bs4` 아나콘다를 설치하면 자동 설치되는 패키지에 포함
- 공식사이트 : https://www.crummy.com/software/BeautifulSoup/
- Documentation : https://www.crummy.com/software/BeautifulSoup/bs4/doc/

In [6]:
import requests #HTTP요청 처리하는 lib
#file://ai/lecNote/
#http://www.
from requests_file import FileAdapter

In [10]:
#로컬에 있는 파일을 웹요청하듯이 읽어오는 작업
s = requests.Session()
s.mount("file://",FileAdapter()) #file://로 시작하는 url을 어댑터가 처리
response=s.get("file:///ai/lecNote/01_python/data/ch14_sample.html") #c:/ai/lecNote/data/ch14_sample.html
response  #html편지봉투   /  편지지 header

In [11]:
# %ls "c:/ai/lecNote/01_python/data/ch14_sample.html"

In [12]:
if response:
    print('해당 url에 접근함')
else:
    print('해당 url에 거부됨')

해당 url에 접근함

In [ ]:
response.status_code
#200:정상
#404:없는페이지

In [13]:
response.content #html의 바이너리 형식의 내용

b'<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n  <meta charset="UTF-8">\r\n</head>\r\n<body>\r\n  <h1 class="greeting css" id="text">Hello, CSS</h1>\r\n  <h1 class="css">Hi, CSS</h1>\r\n  <div id="subject">subject \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90 \xec\x95\x88\xec\x9d\x98 \xeb\x82\xb4\xec\x9a\xa9</div>\r\n  <p>CSS \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\x8a\x94 \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xea\xb3\xb3\xec\x97\x90\xec\x84\x9c \xed\x99\x9c\xec\x9a\xa9\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4</p>\r\n  <div class="contents">\r\n    \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\xa5\xbc \xec\x96\xb4\xeb\x96\xbb\xea\xb2\x8c \xec\x9e\x91\xec\x84\xb1\xed\x95\x98\xeb\x8a\x90\xeb\x83\x90\xec\x97\x90 \xeb\x94\xb0\xeb\x9d\xbc\r\n    <span>\xeb\x8b\xa4\xeb\xa5\xb8<b>\xec\x9a\x94\xec\x86\x8c\xea\xb0\x80 \xeb\xb0\x98\xed\x99\x98</b></span>\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4\r\n  </div>\r\n  <div>CSS \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\x8a\x94 \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xea\xb3\xb3\xec\x97\x90 <b>\xed\x99\x9c\xec\x9a\xa9</b>\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4</div>\r\n</body>\r\n</html>'

In [14]:
print(response.content.decode('utf-8'))

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
</head>
<body>
  <h1 class="greeting css" id="text">Hello, CSS</h1>
  <h1 class="css">Hi, CSS</h1>
  <div id="subject">subject 선택자 안의 내용</div>
  <p>CSS 선택자는 다양한 곳에서 활용됩니다</p>
  <div class="contents">
    선택자를 어떻게 작성하느냐에 따라
    <span>다른<b>요소가 반환</b></span>됩니다
  </div>
  <div>CSS 선택자는 다양한 곳에 <b>활용</b>됩니다</div>
</body>
</html>

In [16]:
response.text

'<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n  <meta charset="UTF-8">\r\n</head>\r\n<body>\r\n  <h1 class="greeting css" id="text">Hello, CSS</h1>\r\n  <h1 class="css">Hi, CSS</h1>\r\n  <div id="subject">subject 선택자 안의 내용</div>\r\n  <p>CSS 선택자는 다양한 곳에서 활용됩니다</p>\r\n  <div class="contents">\r\n    선택자를 어떻게 작성하느냐에 따라\r\n    <span>다른<b>요소가 반환</b></span>됩니다\r\n  </div>\r\n  <div>CSS 선택자는 다양한 곳에 <b>활용</b>됩니다</div>\r\n</body>\r\n</html>'

In [15]:
print(response.text)

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
</head>
<body>
  <h1 class="greeting css" id="text">Hello, CSS</h1>
  <h1 class="css">Hi, CSS</h1>
  <div id="subject">subject 선택자 안의 내용</div>
  <p>CSS 선택자는 다양한 곳에서 활용됩니다</p>
  <div class="contents">
    선택자를 어떻게 작성하느냐에 따라
    <span>다른<b>요소가 반환</b></span>됩니다
  </div>
  <div>CSS 선택자는 다양한 곳에 <b>활용</b>됩니다</div>
</body>
</html>

In [19]:
#html 파싱 객체
from bs4 import BeautifulSoup
soup = BeautifulSoup(response.text, 
                    "html.parser")
#soup

## 1.soup.select_one

In [36]:
#1. soup.select_one('선택자') : 해당 선택자 처음 하나 엘리먼트만 (태그 전체를 가져옴 텍스트만 가져오는게 아님)
el = soup.select_one('h1.greeting.css')
print('el=',el)
print('el,text=>',el.text)
print('el,string=>',el.string)
print('el의 속성들 =>',el.attrs)
print('el의 class속성=>',el.attrs['class'])
print('el의 class속성=>',el.attrs.get('class'))
print('el의 href속성=>',el.attrs.get('href'))
#print('el의 href속성=>',el.attrs['href']) []로 불러낼때는 error 발생으로 get 함수 사용이 더 좋다
print('el의 name=>',el.name)

el= <h1 class="greeting css" id="text">Hello, CSS</h1>
el,text=> Hello, CSS
el,string=> Hello, CSS
el의 속성들 => {'class': ['greeting', 'css'], 'id': 'text'}
el의 class속성=> ['greeting', 'css']
el의 class속성=> ['greeting', 'css']
el의 href속성=> None
el의 name=> h1

## 2.soup.select

In [47]:
# 2.soup.select('선택자') : 해당 선택자 엘리먼트 다 list로
els = soup.select('h1.css')
print('els =>',els)
print('els들의 text',els[0].text)
print('els들의 text',[el.text for el in els])
print('els들의 string',[el.string for el in els])
print('els들의 속성들',[el.attrs for el in els])
print('els들의 class속성들',[el.attrs.get('class') for el in els])

els => [<h1 class="greeting css" id="text">Hello, CSS</h1>, <h1 class="css">Hi, CSS</h1>]
els들의 text Hello, CSS
els들의 text ['Hello, CSS', 'Hi, CSS']
els들의 string ['Hello, CSS', 'Hi, CSS']
els들의 속성들 [{'class': ['greeting', 'css'], 'id': 'text'}, {'class': ['css']}]
els들의 class속성들 [['greeting', 'css'], ['css']]

## 3.soup.find

In [57]:
# 3.soup.find('태그', 속성) vs soup.select_one('선택자') : 해당 속성을 갖은 태그 처음 하나만 
print('select_one:', soup.select_one('h1.css'))
print('find      :', soup.find('h1',{'class':'css'}))
# print('find      :', soup.find('h1',{'css'})) 왜 되는지 확인!
print('find      :', soup.find('h1',class_='css'))
print()
print('select_one:',soup.select_one('h1#text'))
print('select_one:',soup.find('h1',{'id':'text'}))

select_one: <h1 class="greeting css" id="text">Hello, CSS</h1>
find      : <h1 class="greeting css" id="text">Hello, CSS</h1>
find      : <h1 class="greeting css" id="text">Hello, CSS</h1>

select_one: <h1 class="greeting css" id="text">Hello, CSS</h1>
select_one: <h1 class="greeting css" id="text">Hello, CSS</h1>

## 4.soup.find_all

In [66]:
# 3.soup.find_all('태그', 속성) vs soup.select('선택자') : 해당 엘리먼트 다 list로
print('모든 h1.css 와 span태그 :', soup.select('h1.css, span'))
print('모든 h1.css 와 span태그 :', soup.find_all(['h1'],class_='css')+soup.find_all('span'))

모든 h1.css 와 span태그 : [<h1 class="greeting css" id="text">Hello, CSS</h1>, <h1 class="css">Hi, CSS</h1>, <span>다른<b>요소가 반환</b></span>]
모든 h1.css 와 span태그 : [<h1 class="greeting css" id="text">Hello, CSS</h1>, <h1 class="css">Hi, CSS</h1>, <span>다른<b>요소가 반환</b></span>]

In [77]:
#없는 Element 찾기
print('find_all(빈list) : ', soup.find_all('a'))
print('find(None)       : ', soup.find('a'))
print('select(빈list)   : ', soup.select('a'))
print('select_one(None) : ', soup.select_one('a'))

find_all(빈list) :  []
find(None)       :  None
select(빈list)   :  []
select_one(None) :  None

# 2절. 정적 웹데이터 수집(정적 웹크롤링)
## 2.1 BeautifulSoup 모듈을 활용한 html 웹데이터 수집
### 1) 환율정보 가져오기(네이버증권>시장지표)

 - https://finance.naver.com/marketindex/
 
     * 크롤링 허용범위는 사이트마다 ~/robots.txt에서 확인할 수 있음
         - Allow : 크롤링 허용 가능한 폴더
         - Disallow : 크롤링 제한 폴더
       ex )https://finance.naver.com/robots.txt 로 검색하면 
       User-agent: *
        Disallow: /
        User-agent: yeti
        Disallow: /
        Allow: /sise/
        Allow: /research/
        Allow: /marketindex/
        Allow: /fund/
        Allow: /template/head_js.naver
        Allow: /world/
        Allow: /item/board.naver?code=*
        Disallow: /item/board.naver?code=*&page=*
        Disallow : /fund/news/
        Disallow : /marketindex/news/

In [86]:
#soup 객체 생성 방법1
import requests
from bs4 import BeautifulSoup
url = 'https://finance.naver.com/marketindex/'
response = requests.get(url)
response # Response 객체
print(response.status_code)
#response.content
#print(response.text)   #이제 soup객체 만들수 있다
soup = BeautifulSoup(response.text,'html.parser')   # soup객체 만드는 방법 1

200

In [99]:
#soup 객체 생성 방법2
from urllib.request import urlopen
url = 'https://finance.naver.com/marketindex/'
response = urlopen(url)
#response # HTTPResponse
print(response.status)
#response.read().decode('cp949')
soup = BeautifulSoup(response,'html.parser')

200

In [114]:
p= '1,417.70'
float(p.replace(',','')) # ,없애는 방법1 replace
float(''.join(p.split(',')))# ,없애는 방법1 ,로 split 후 ''으로 다시join 후 float

1417.7

In [125]:
#div.head_info 밑의 span.value (find계열)
prices = []
headinfos = soup.find_all('div',class_='head_info')
for headinfo in headinfos:
#    print(headinfo)
    price=headinfo.find('span',class_='value')
    prices.append(float(''.join(price.text.split(','))))
print(prices)

[1417.7, 889.17, 1635.6, 210.09, 159.24, 1.1541, 1.3507, 99.71, 83.2, 1863.92, 4441.1, 200855.05]

In [126]:
#span.value(find계열)
price_els = soup.find_all('span', class_='value')
prices = [round(float(price.text.replace(',','')),1) for price in price_els]
print(prices)

[1417.7, 889.2, 1635.6, 210.1, 159.2, 1.2, 1.4, 99.7, 83.2, 1863.9, 4441.1, 200855.0]

In [138]:
#div.head_info 밑의 span.value
price_els =soup.select('div.head_info > span.value')
#price_els
title_els =soup.select('h3.h_lst > span.blind')
title_els

[<span class="blind">미국 USD</span>,
 <span class="blind">일본 JPY(100엔)</span>,
 <span class="blind">유럽연합 EUR</span>,
 <span class="blind">중국 CNY</span>,
 <span class="blind">달러/일본 엔</span>,
 <span class="blind">유로/달러</span>,
 <span class="blind">영국 파운드/달러</span>,
 <span class="blind">달러인덱스</span>,
 <span class="blind">WTI</span>,
 <span class="blind">휘발유</span>,
 <span class="blind">국제 금</span>,
 <span class="blind">국내 금</span>]

In [150]:
# 단위들 : div.head_info > span > span.blind
unit_els = soup.select('div.head_info > span > span.blind')
unit_els
units= [unit_el.string for unit_el in unit_els]
units.insert(7,'')  #insert로 달러인덱스 단위에 빈문자 추가 
units

['원', '원', '원', '원', '엔', '달러', '달러', '', '달러', '원', '달러', '원']

In [152]:
# 상승/하락 : div.head_info > span.blind
trend_els = soup.select('div.head_info > span.blind')
trends=[trend.string for trend in trend_els]
trends

['상승', '상승', '상승', '상승', '상승', '하락', '하락', '상승', '상승', '하락', '상승', '상승']

In [158]:
# for idx in range(len(title_els)):
#     print("{}  :   {}   {}   -{}".format(title_els[idx].text,
#                                 price_els[idx].text,
#                                 units[idx],
#                                 trends[idx]))
# 좋은 방법 아님!!

미국 USD  :   1,417.70   원   -상승
일본 JPY(100엔)  :   889.17   원   -상승
유럽연합 EUR  :   1,635.60   원   -상승
중국 CNY  :   210.09   원   -상승
달러/일본 엔  :   159.2400   엔   -상승
유로/달러  :   1.1541   달러   -하락
영국 파운드/달러  :   1.3507   달러   -하락
달러인덱스  :   99.7100      -상승
WTI  :   83.2   달러   -상승
휘발유  :   1863.92   원   -하락
국제 금  :   4441.1   달러   -상승
국내 금  :   200855.05   원   -상승

In [ ]:
for title, price, unit, trend in zip(title_els, price_els, units, trend_els):
    print("{}:{}{}-{}".format(title.text,price.text,unit,trend.text))
##이방법을 필히 기억할 것

In [175]:
import pandas as pd
import numpy as np
data=[]
for title, price, unit, trend in zip(title_els, price_els, units, trend_els):
    data.append({'title':title.text,'price':float(price.text.replace(',','')),'unit':unit,'trend':trend.text})
pd.DataFrame(data)#.to_csv('data/file.csv',index=False)

           title        price unit trend
0         미국 USD    1417.7000    원    상승
1   일본 JPY(100엔)     889.1700    원    상승
2       유럽연합 EUR    1635.6000    원    상승
3         중국 CNY     210.0900    원    상승
4        달러/일본 엔     159.2400    엔    상승
5          유로/달러       1.1541   달러    하락
6      영국 파운드/달러       1.3507   달러    하락
7          달러인덱스      99.7100         상승
8            WTI      83.2000   달러    상승
9            휘발유    1863.9200    원    하락
10          국제 금    4441.1000   달러    상승
11          국내 금  200855.0500    원    상승

In [171]:
#넘파이 판다스 부동산 분석시스템 복습할것

In [181]:
data=[]
for title, price, unit, trend in zip(title_els, price_els, units, trend_els):
    data.append([title.text,float(price.text.replace(',','')),unit,trend.text])
pd.DataFrame(data,columns=['title','price','unit','trend'])

           title        price unit trend
0         미국 USD    1417.7000    원    상승
1   일본 JPY(100엔)     889.1700    원    상승
2       유럽연합 EUR    1635.6000    원    상승
3         중국 CNY     210.0900    원    상승
4        달러/일본 엔     159.2400    엔    상승
5          유로/달러       1.1541   달러    하락
6      영국 파운드/달러       1.3507   달러    하락
7          달러인덱스      99.7100         상승
8            WTI      83.2000   달러    상승
9            휘발유    1863.9200    원    하락
10          국제 금    4441.1000   달러    상승
11          국내 금  200855.0500    원    상승

### 2) 이번주 로또 번호 출력
- 방법2에서 User-Agent를 추가하여 soup생성
- https://search.daum.net/search?w=tot&DA=YZR&t__nil_searchbox=btn&q=lotto (다음에서 lotto검색)
```
    1236회((2026.08.08 추첨)
    당첨번호 [12, 18, 21, 29, 34, 38]
    보너스 10
```

In [188]:
#방법1
import requests
from bs4 import BeautifulSoup
url = 'https://search.daum.net/search?w=tot&DA=YZR&t__nil_searchbox=btn&q=lotto'
response = requests.get(url)
print('response의 상태 : ',response.status_code) # 200값 나오는지 확인
soup = BeautifulSoup(response.text,'html.parser')
#soup --> 정상 출력으로 가능

response의 상태 :  200

In [202]:
#방법2
from urllib.request import urlopen, Request
url = 'https://search.daum.net/search?w=tot&DA=YZR&t__nil_searchbox=btn&q=lotto'
headers={'User-agent' : 
         'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36'}
request = Request(url, headers=headers)

response = urlopen(request)
print('response의 상태 ',response.status)
soup = BeautifulSoup(response,'html.parser')
#soup

response의 상태  200

In [ ]:
#     1236회((2026.08.08 추첨)
#     당첨번호 [12, 18, 21, 29, 34, 38]
#     보너스 10

In [235]:
times = soup.select_one('div.prize span.f_red').text
date = soup.select_one('div.prize > span.date').text
title1= soup.select_one('div.prize > strong').text[-4:]
lotto_numbers = soup.select('div.lottonum > span.ball:nth-last-child(n+3)')
title2= soup.select_one('div.lottonum span.screen_out').text
bonus_number=soup.select_one('div.lottonum > span.bg_ball1').text
print(times,date)
print(title1,[int(numbers.text) for numbers in lotto_numbers])
print(title2,bonus_number)

1236회 (2026.08.08 추첨)
당첨번호 [12, 18, 21, 29, 34, 38]
보너스 10

In [218]:
# lotto_numbers = soup.select('div.lottonum > span.ball')[:-2]
# lotto_numbers

[<span class="ball bg_ball2">12</span>,
 <span class="ball bg_ball2">18</span>,
 <span class="ball bg_ball3">21</span>,
 <span class="ball bg_ball3">29</span>,
 <span class="ball bg_ball4">34</span>,
 <span class="ball bg_ball4">38</span>]

In [250]:
##select 를 find로 변경해서 작성해봄

# times = soup.select_one('div.prize span.f_red').text
prize= soup.find('div',class_='prize')
times = prize.find('span',class_='f_red').text
times

# date = soup.select_one('div.prize > span.date').text
date = prize.find('span',class_='date').text
date

# title1= soup.select_one('div.prize > strong').text[-4:]
title1=prize.find('strong').text[-4:]
title1

# lotto_numbers = soup.select('div.lottonum > span.ball:nth-last-child(n+3)')
lottonum=soup.find('div',class_='lottonum')
lottonumbers=lottonum.find_all('span',class_='ball')[:-2]
lottonumbers

# title2= soup.select_one('div.lottonum span.screen_out').text
title2=lottonum.find('span', class_='screen_out').text
title2

# bonus_number=soup.select_one('div.lottonum > span.bg_ball1').text
bonus_number=lottonum.find('span',class_='bg_ball1').text
bonus_number

print(times,date)
print(title1,[int(numbers.text) for numbers in lotto_numbers])
print(title2,bonus_number)

1236회 (2026.08.08 추첨)
당첨번호 [12, 18, 21, 29, 34, 38]
보너스 10

### 3) 다음 뉴스 검색 리스트
```
no title href
0 타이틀1 http://~
1 타이틀2 http://~
2 타이틀3 http://~
```

In [170]:
#방법1
import requests
from bs4 import BeautifulSoup
word= '비트코인'
url = f'https://search.daum.net/search?w=news&q={word}'
#url = 'https://search.daum.net/search?w=news&q={}'.format(word)
print(url)
response = requests.get(url)
print(response.status_code)
soup =BeautifulSoup(response.text,'html.parser')

https://search.daum.net/search?w=news&q=비트코인
200

In [171]:
#방법1
import requests
from bs4 import BeautifulSoup
word= '스포츠'
url = f'https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y&cluster_page=1&q={word}&p=1'
#url = 'https://search.daum.net/search?w=news&q={}'.format(word)
print(url)
response = requests.get(url)
print(response.status_code)
soup =BeautifulSoup(response.text,'html.parser')

https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y&cluster_page=1&q=스포츠&p=1
200

In [172]:
#방법2
from urllib.request import urlopen, Request
from urllib.parse import quote #ASCII 코드 처리해주는 라이브러리
#word='%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8' ##브라우저 창에서 복사 붙여넣기 하면 ASCII 코드로 변환됨
word=quote('스포츠')
url = f'https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y&cluster_page=1&q={word}&p=1'
print(url)
headers={'User-agent' : 
         'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36'}
#request = Request(url, headers=headers)
request = Request(url)
request.add_header('User-agent',
                   'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36')
response = urlopen(request)
print(response.status)
soup=BeautifulSoup(response,'html.parser')
#soup

https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y&cluster_page=1&q=%EC%8A%A4%ED%8F%AC%EC%B8%A0&p=1
200

In [173]:
items_find_list =[] # 검색한 결과를 담을 dict 리스트
items_el=soup.select('div.item-title > strong.tit-g.clamp-g > a')
for idx, item in enumerate(items_el):
    #print(idx,item)
    items_find_list.append({'no':idx,
                            'tile':item.text,
                            'link':item.attrs.get('href')})
import pandas as pd
pd.DataFrame(items_find_list).head(3)

,no,tile,link
0,0,"켄뷰, 스포츠약학회와 ‘타이레놀ER 스포츠 통증 세미나’ 성료",http://v.daum.net/v/20260811093227508
1,1,"여수시, 2027년 대통령배 전국 아마추어 e스포츠 대회·전국 장애인 e스포츠 대...",http://v.daum.net/v/20260814113409886
2,2,게임·e스포츠 협단체 공동 성명 “게임 제작비·e스포츠대회 운영비 세액공제”,http://v.daum.net/v/20260814141802213

In [174]:
items_find_list =[] # 검색한 결과를 담을 2차원 리스트
items_el=soup.select('div.item-title > strong.tit-g.clamp-g > a')
for idx, item in enumerate(items_el):
    items_find_list.append([idx,item.text,item.attrs.get('href')])
pd.DataFrame(items_find_list,columns=['순번','제목','링크'])

,순번,제목,링크
0,0,"켄뷰, 스포츠약학회와 ‘타이레놀ER 스포츠 통증 세미나’ 성료",http://v.daum.net/v/20260811093227508
1,1,"여수시, 2027년 대통령배 전국 아마추어 e스포츠 대회·전국 장애인 e스포츠 대...",http://v.daum.net/v/20260814113409886
2,2,게임·e스포츠 협단체 공동 성명 “게임 제작비·e스포츠대회 운영비 세액공제”,http://v.daum.net/v/20260814141802213
3,3,"한국e스포츠협회-마포진로직업체험지원센터, 청소년 e스포츠 진로 탐색 나선다",http://v.daum.net/v/20260814163449710
4,4,"강동구, 청소년 스포츠 '런런리그' 개최 [동네방네]",http://v.daum.net/v/20260814074648775
5,5,"청소년스포츠한마당 댄스스포츠대회, 23일 강릉서 막 올라",http://v.daum.net/v/20260813143341601
6,6,"경주, e스포츠 축제장 변신한다…대통령배 KeG 결선 등 개최",http://v.daum.net/v/20260814105710059
7,7,"'만족도 97.4%' 용인, 스포츠산업 유망주 대상 '구단 탐방 프로그램' 성료",http://v.daum.net/v/20260813175748079
8,8,경주서 ‘e스포츠 축제’ 잇따라 열린다,http://v.daum.net/v/20260814134549114
9,9,스포츠 선진국을 향하여 [투데이 窓/반영은],http://v.daum.net/v/20260814083137708

In [176]:
#다음 뉴스 검색 함수(원하는 키워드, 원하는 페이지로)
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def collect_list(keyword, page):
    'keyword로 해당 page에 검색한 결과 dict list return'
    #url = f'https://search.daum.net/search?w=news&q={keyword}&p={page}'
    url= 'https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y&cluster_page=1'
    params ={'q':keyword, 'p':page}
    response=requests.get(url,params=params)ㄴ
    soup = BeautifulSoup(response.text, 'html.parser')
    items_find_list=[]
    items_el=soup.select('div.item-title > strong.tit-g.clamp-g > a')
    for idx, item in enumerate(items_el):
        items_find_list.append({'no':(page-1)*10+idx,
                                'title':item.text,      
                                'link':item.attrs.get('href')})
    return items_find_list

SyntaxError: invalid syntax (4096813566.py, line 12)

In [177]:
items_find_list

[[0,
  ' 켄뷰, 스포츠약학회와 ‘타이레놀ER 스포츠 통증 세미나’ 성료 ',
  'http://v.daum.net/v/20260811093227508'],
 [1,
  ' 여수시, 2027년 대통령배 전국 아마추어 e스포츠 대회·전국 장애인 e스포츠 대회 유치 확정 ',
  'http://v.daum.net/v/20260814113409886'],
 [2,
  ' 게임·e스포츠 협단체 공동 성명 “게임 제작비·e스포츠대회 운영비 세액공제” ',
  'http://v.daum.net/v/20260814141802213'],
 [3,
  ' 한국e스포츠협회-마포진로직업체험지원센터, 청소년 e스포츠 진로 탐색 나선다 ',
  'http://v.daum.net/v/20260814163449710'],
 [4,
  " 강동구, 청소년 스포츠 '런런리그' 개최 [동네방네] ",
  'http://v.daum.net/v/20260814074648775'],
 [5,
  ' 청소년스포츠한마당 댄스스포츠대회, 23일 강릉서 막 올라 ',
  'http://v.daum.net/v/20260813143341601'],
 [6,
  ' 경주, e스포츠 축제장 변신한다…대통령배 KeG 결선 등 개최 ',
  'http://v.daum.net/v/20260814105710059'],
 [7,
  " '만족도 97.4%' 용인, 스포츠산업 유망주 대상 '구단 탐방 프로그램' 성료 ",
  'http://v.daum.net/v/20260813175748079'],
 [8, ' 경주서 ‘e스포츠 축제’ 잇따라 열린다 ', 'http://v.daum.net/v/20260814134549114'],
 [9, ' 스포츠 선진국을 향하여 [투데이 窓/반영은] ', 'http://v.daum.net/v/20260814083137708']]

In [16]:
#collect_list('한국',1)

In [21]:
result=[] #해당 키워드 원하는 페이지 수만큼 검색한 결과 담을 변수 dict list
pages = 3
for page in range(1,pages+1):
    print(f"=={page} 페이지 수집 중==")
    item_result = collect_list('이강인',page)
    result.append(item_result)
result  ## 2차원리스트로 됨

==1 페이지 수집 중==
==2 페이지 수집 중==
==3 페이지 수집 중==

[[{'no': 0,
   'title': ' 스페인서 자란 이강인도 놀랄 정도라니…“아틀레티코, 지금껏 내가 경험한 것과 정말 다르다” ',
   'link': 'http://v.daum.net/v/20260813085927711'},
  {'no': 1,
   'title': ' 손흥민 이어 토트넘 주장 맡았던 로메로, 이제 이강인과 동행...AT 마드리드 이적 임박 ',
   'link': 'http://v.daum.net/v/20260813090849093'},
  {'no': 2,
   'title': " 817억 '이강인 대체자', 데뷔전서 전반 끝나자마자 '교체 아웃'…준수한 활약으로 다음 경기 기대케 했다 ",
   'link': 'http://v.daum.net/v/20260813081009265'},
  {'no': 3,
   'title': ' 韓 축구 초대박 인연, 손흥민 이어 이강인과 함께 뛴다! HERE WE GO “로메로, 토트넘 떠나 아틀레티코 이적 확정” ',
   'link': 'http://v.daum.net/v/20260813085639594'},
  {'no': 4,
   'title': " '토트넘 주장→이강인 동료' 로메로의 선택은 아스널도 바르셀로나도 아니었다… 아틀레티코 마드리드행 임박 ",
   'link': 'http://v.daum.net/v/20260813095651295'},
  {'no': 5,
   'title': ' 이강인 떠난 PSG, 빌라 꺾고 UEFA 슈퍼컵 2연패 달성 ',
   'link': 'http://v.daum.net/v/20260813090444955'},
  {'no': 6,
   'title': ' "이강인, 아이들에게 다정해" 현지 첫인상 호평의 연속…"매 훈련 세션 초집중" AT 마드리드 첫 시즌 \'희망적\' ',
   'link': 'http://v.daum.net/v/20260813031332566'},
  {'no': 7,
   'title': ' ‘이강인 파급효과 미쳤다!’ ATM, 한국 기업과 스폰서십 계약...“320억 수익 예상” ',
   'link': 'http://v.daum.net/v/20260813012643119'},
  {'no': 8,
   'title': ' "초대박!" \'HERE WE GO 떴다\' 韓 에이스 이강인 든든한 조력자 뜬다…크리스티안 로메로, 토트넘 떠나 아틀레티코 마드리드 이적 임박 ',
   'link': 'http://v.daum.net/v/20260813082732672'},
  {'no': 9,
   'title': " 의욕 미쳤다! 마침내 아틀레티코 훈련장 입성한 이강인, 예정보다 일찍 훈련 합류...西언론도 극찬 '1초도 허비하고 싶지 않아해' ",
   'link': 'http://v.daum.net/v/20260812204455555'}],
 [{'no': 10,
   'title': ' [오피셜] 이강인 없어도 흔들리지 않는다…PSG, 챔스 2연패 이어 슈퍼컵까지 2연패 영예 ',
   'link': 'http://v.daum.net/v/20260813093645351'},
  {'no': 11,
   'title': ' [IS 인터뷰] \'이강인 효과\' 이상을 넘보다…라리가 아시아 디렉터 "9년의 노력, 이제 결과로" ',
   'link': 'http://v.daum.net/v/20260813001042608'},
  {'no': 12,
   'title': ' "와우 한국 팬 어메이징!" 한국에서 뛰는 걸 즐긴 필 포든 "이강인은 훌륭한 선수" ',
   'link': 'http://v.daum.net/v/20260813034907622'},
  {'no': 13,
   'title': ' "손흥민 떠나자, 이강인 입단 동기" \'HERE WE GO\', \'BBC\' 모두 떴다! 토트넘 \'최악의 주장\' 로메로, 아틀레티코 마드리드 4000만유로 이적 확정 ',
   'link': 'http://v.daum.net/v/20260813092155680'},
  {'no': 14,
   'title': ' "초대박!" \'4000만 유로 에이스\' 이강인 효과 미쳤다…AT 마드리드 새 메인 후원 2000만 유로 체결 임박→유니폼 1만장 \'완판\' ',
   'link': 'http://v.daum.net/v/20260812164734181'},
  {'no': 15,
   'title': " '북중미월드컵 4강 멤버만 10명, 지원군이 왔다'…이강인 새 동료 아틀레티코 마드리드 합류 ",
   'link': 'http://v.daum.net/v/20260813050330671'},
  {'no': 16,
   'title': " '이강인 효과'에 웃는 ATM…유니폼 완판에 한국 기업 후원까지 ",
   'link': 'http://v.daum.net/v/20260813060229185'},
  {'no': 17,
   'title': ' "ATM 유니폼 더 많아졌으면" 이강인 말 떨어지자 현실 됐다...1만장 완판+스폰서 654억 \'광풍\' ',
   'link': 'http://v.daum.net/v/20260812235936270'},
  {'no': 18,
   'title': " 'HERE WE GO' 손흥민과 토트넘서 맹활약한 로메로, 이강인과 한솥밥... 아틀레티코행 확정 '이적료 654억' ",
   'link': 'http://v.daum.net/v/20260813081409356'},
  {'no': 19,
   'title': ' \'와\' 역사상 이런 한국 선수 있었나…"이강인? 그리즈만 유니폼 판매랑 5배 기록할 듯" 전망 ',
   'link': 'http://v.daum.net/v/20260812124928587'}],
 [{'no': 20,
   'title': ' \'공격 차단 후 이강인에게 연결\' 로메로, 토트넘 떠나 ATM 이적...로마노, "HERE WE GO" ',
   'link': 'http://v.daum.net/v/20260813081450366'},
  {'no': 21,
   'title': " '와' 이강인 효과 미쳤다...아틑레티코 '320억' 스폰서 수익+'No.7' 유니폼 그리즈만 '4배', 이적료 '640억' 역대급 '저점 매수?' ",
   'link': 'http://v.daum.net/v/20260813063527646'},
  {'no': 22,
   'title': " 토트넘 '손흥민 후임 주장' 로메로, 이강인과 한솥밥…아틀레티코행 임박 ",
   'link': 'http://v.daum.net/v/20260813084249147'},
  {'no': 23,
   'title': " 마침내 'HERE WE GO' 떴다…손흥민 주장 완장 물려받은 로메로, 토트넘 떠나 AT 마드리드 이적→'韓 축구 에이스' 이강인과 한솥밥 ",
   'link': 'http://v.daum.net/v/20260813074637704'},
  {'no': 24,
   'title': ' \'NEW 7번\' 이강인 피할 수 없는 거대한 부담감...\'새 스승\' 시메오네 깜짝 고백 "난 천재와 함께 일 했었다" ',
   'link': 'http://v.daum.net/v/20260812215047992'},
  {'no': 25,
   'title': ' 이강인, 드디어 마드리드 입성…현지 언론 "올시즌 핵심 선수" ',
   'link': 'http://v.daum.net/v/20260812205017645'},
  {'no': 26,
   'title': ' [속보] HERE WE GO 나왔다! \'토트넘 최악의 주장\' 로메로, 이강인과 한솥밥 임박…"아틀레티코 마드리드행" ',
   'link': 'http://v.daum.net/v/20260813064838836'},
  {'no': 27,
   'title': ' ‘이강인 뉴 파트너’ 알바레스, ATM 면담 거절에 실망...팬들은 ‘사과 요구’ ',
   'link': 'http://v.daum.net/v/20260812221150369'},
  {'no': 28,
   'title': ' \'열정이 넘친다\' 이강인, 스페인 도착하자마자 훈련장으로...마르카 "1초도 허비 안 해" ',
   'link': 'http://v.daum.net/v/20260813032937589'},
  {'no': 29,
   'title': " '이강인과 한솥밥 먹는다' HERE WE GO 확인, 아틀레티코 마드리드↔토트넘, 아르헨티나 국대 수비수 로메로 완전 이적 합의..'이적료 4000만유로, 메디컬 테스트만 남았다' ",
   'link': 'http://v.daum.net/v/20260813065153870'}]]

In [23]:
result=[] #해당 키워드 원하는 페이지 수만큼 검색한 결과 담을 변수 dict list
pages = 3
for page in range(1,pages+1):
    print(f"=={page} 페이지 수집 중==")
    item_result = collect_list('이강인',page)
    result.extend(item_result)
    time.sleep(3)

==1 페이지 수집 중==
==2 페이지 수집 중==
==3 페이지 수집 중==

In [24]:
pd.DataFrame(result)

,no,title,link
0,0,"스페인서 자란 이강인도 놀랄 정도라니…“아틀레티코, 지금껏 내가 경험한 것과 정말...",http://v.daum.net/v/20260813085927711
1,1,"韓 축구 초대박 인연, 손흥민 이어 이강인과 함께 뛴다! HERE WE GO “로...",http://v.daum.net/v/20260813085639594
2,2,"817억 '이강인 대체자', 데뷔전서 전반 끝나자마자 '교체 아웃'…준수한 활약으...",http://v.daum.net/v/20260813081009265
3,3,"손흥민 이어 토트넘 주장 맡았던 로메로, 이제 이강인과 동행...AT 마드리드 이...",http://v.daum.net/v/20260813090849093
4,4,"""초대박!"" 'HERE WE GO 떴다' 韓 에이스 이강인 든든한 조력자 뜬다…크...",http://v.daum.net/v/20260813082732672
5,5,'토트넘 주장→이강인 동료' 로메로의 선택은 아스널도 바르셀로나도 아니었다… 아틀...,http://v.daum.net/v/20260813095651295
6,6,"‘이강인 파급효과 미쳤다!’ ATM, 한국 기업과 스폰서십 계약...“320억 수...",http://v.daum.net/v/20260813012643119
7,7,"""이강인, 아이들에게 다정해"" 현지 첫인상 호평의 연속…""매 훈련 세션 초집중"" ...",http://v.daum.net/v/20260813031332566
8,8,"이강인 떠난 PSG, 2026 UEFA 슈퍼컵 2연패",http://v.daum.net/v/20260813092251717
9,9,"의욕 미쳤다! 마침내 아틀레티코 훈련장 입성한 이강인, 예정보다 일찍 훈련 합류....",http://v.daum.net/v/20260812204455555
10,10,"[IS 인터뷰] '이강인 효과' 이상을 넘보다…라리가 아시아 디렉터 ""9년의 노력...",http://v.daum.net/v/20260813001042608
11,11,"[오피셜] 이강인 없어도 흔들리지 않는다…PSG, 챔스 2연패 이어 슈퍼컵까지 2...",http://v.daum.net/v/20260813093645351
12,12,"'북중미월드컵 4강 멤버만 10명, 지원군이 왔다'…이강인 새 동료 아틀레티코 마...",http://v.daum.net/v/20260813050330671
13,13,"""와우 한국 팬 어메이징!"" 한국에서 뛰는 걸 즐긴 필 포든 ""이강인은 훌륭한 선수""",http://v.daum.net/v/20260813034907622
14,14,"""초대박!"" '4000만 유로 에이스' 이강인 효과 미쳤다…AT 마드리드 새 메인...",http://v.daum.net/v/20260812164734181
15,15,"'열정이 넘친다' 이강인, 스페인 도착하자마자 훈련장으로...마르카 ""1초도 허비...",http://v.daum.net/v/20260813032937589
16,16,"""ATM 유니폼 더 많아졌으면"" 이강인 말 떨어지자 현실 됐다...1만장 완판+스...",http://v.daum.net/v/20260812235936270
17,17,"""손흥민 떠나자, 이강인 입단 동기"" 'HERE WE GO', 'BBC' 모두 떴...",http://v.daum.net/v/20260813092155680
18,18,"'와' 역사상 이런 한국 선수 있었나…""이강인? 그리즈만 유니폼 판매랑 5배 기록...",http://v.daum.net/v/20260812124928587
19,19,'이강인 효과'에 웃는 ATM…유니폼 완판에 한국 기업 후원까지,http://v.daum.net/v/20260813060229185
20,20,"'HERE WE GO' 손흥민과 토트넘서 맹활약한 로메로, 이강인과 한솥밥... ...",http://v.daum.net/v/20260813081409356
21,21,'NEW 7번' 이강인 피할 수 없는 거대한 부담감...'새 스승' 시메오네 깜짝...,http://v.daum.net/v/20260812215047992
22,22,"이강인, 드디어 마드리드 입성…현지 언론 ""올시즌 핵심 선수""",http://v.daum.net/v/20260812205017645
23,23,"'공격 차단 후 이강인에게 연결' 로메로, 토트넘 떠나 ATM 이적...로마노, ...",http://v.daum.net/v/20260813081450366
24,24,"토트넘 '손흥민 후임 주장' 로메로, 이강인과 한솥밥…아틀레티코행 임박",http://v.daum.net/v/20260813084249147
25,25,"""손흥민 절친X토트넘 캡틴→결국 이강인과 한솥밥"" 로메로, 아틀레티코 654억원 ...",http://v.daum.net/v/20260813072656391
26,26,'와' 이강인 효과 미쳤다...아틑레티코 '320억' 스폰서 수익+'No.7' 유...,http://v.daum.net/v/20260813063527646
27,27,"[속보] HERE WE GO 나왔다! '토트넘 최악의 주장' 로메로, 이강인과 한...",http://v.daum.net/v/20260813064838836
28,28,"‘이강인 뉴 파트너’ 알바레스, ATM 면담 거절에 실망...팬들은 ‘사과 요구’",http://v.daum.net/v/20260812221150369
29,29,"마침내 'HERE WE GO' 떴다…손흥민 주장 완장 물려받은 로메로, 토트넘 떠...",http://v.daum.net/v/20260813074637704

In [33]:
keywords = ['스파이더맨','마블']
pages=3
result0=[] #keyword[0] 1~pages페이지까지 검색한 결과 dict list
result1=[] #keyword[1] 1~pages페이지까지 검색한 결과 dict list  #중첩 for문 

for i, keyword in enumerate(keywords):
    print(f"= = {i+1}번째 검색어{keyword}검색결과 수집중({pages}페이지)입니다= =")
    for page in range(1, page+1):
        if i==0:
            result0.extend(collect_list(keyword,page))
        else:  
            result1.extend(collect_list(keyword,page))
        time.sleep(3)

= = 1번째 검색어스파이더맨검색결과 수집중(3페이지)입니다= =
= = 2번째 검색어마블검색결과 수집중(3페이지)입니다= =

In [36]:
result0_df=pd.DataFrame(result0)
result1_df=pd.DataFrame(result1)
result0_df.sample()

,no,title,link
4,4,"[정태윤의 별달린다] ""브랜드 뉴 피터"" (스파이더맨4 ★★★☆)",http://v.daum.net/v/20260813090327918

In [37]:
result1_df.sample()

,no,title,link
3,3,"‘마블 캐릭터’ 한강 밤하늘 출격… 드론 2000대 역대 최대 [오늘, 특별시]",http://v.daum.net/v/20260811145644551

In [40]:
result0_df.to_csv(f'data/ch14_{keywords[0]}.csv',index=False,encoding='cp949')
result0_df.to_csv(f'data/ch14_{keywords[1]}.csv',index=False,encoding='cp949')

### 4) User-Agent를 추가하여 크롤링
- request.get(url), urlopen(url) 함수를 사용하면 크롤링이 막혀있는 사이트
- 방법2에서 User-Agent를 추가하여 크롤링

- 멜론 https://www.melon.com/robots.txt 에서 일부 경로는 User-Agent에 봇이 지정

In [46]:
# 방법1
import requests
from bs4 import BeautifulSoup
url = 'https://www.melon.com/chart/'
melonResponse = requests.get(url) 
print(melonResponse.status_code)
soup=BeautifulSoup(melonResponse.text,'html.parser')
## 막혀있어서 방법 1로는 불가

406

In [49]:
##방법2
from urllib.request import urlopen
from bs4 import BeautifulSoup
url = 'https://www.melon.com/chart/'
#melonResponse = urlopen(url)  #HTTP Error 406: Not Acceptable

In [53]:
#User=Agent를 추가하여 방법2
from urllib.request import urlopen, Request
from bs4 import BeautifulSoup
url = 'https://www.melon.com/chart/'
header ={'User-agent' :'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36'}
#melonpage = Request(url,headers=headers)
melonpage=Request(url)
melonpage.add_header('User-agent',
                     'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36')
melonResponse = urlopen(melonpage)
print(melonResponse.status)
soup = BeautifulSoup(melonResponse, 'html.parser')
soup

200

<!DOCTYPE html>

<html lang="ko">
<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<title>멜론차트&gt;TOP100&gt;멜론</title>
<meta content="음악서비스, 멜론차트, 멜론TOP100, 최신음악, 인기가요, 뮤직비디오, 앨범, 플레이어, 스트리밍, 다운로드, 아티스트플러스, 아티스트채널" name="keywords"/>
<meta content="No.1 뮤직플랫폼 멜론! 최신 트렌드부터 나를 아는 똑똑한 음악추천까지!" name="description"/>
<meta content="ee85ff6db1fa8f2226bcb671ecb2bcdbcffb6f8b" name="naver-site-verification"/>
<meta content="q4tbTQhmxa4La3OdNLsNOCxrJ_WV6lUlBFrFW4-HqQc" name="google-site-verification"/>
<meta content="4022717807957185" property="fb:app_id"/>
<meta content="Melon" property="og:title"/>
<meta content="https://cdnimg.melon.co.kr/resource/image/web/common/logo_melon142x99.png" property="og:image"/>
<meta content="음악이 필요한 순간, 멜론" property="og:description"/>
<meta content="http://www.melon.com/chart/" property="og:url"/>
<meta content="website" property="og:type"/>
<meta content="멜론" property="og:site_name"/>
<meta content="width=device-width" name="viewport"/>
<link href="/favicon.ico?2" id="favicon" rel="shortcut icon" type="image/x-icon"/>
<link href="/resource/style/web/common/melonweb_layout.css?tm=20260604" rel="stylesheet" type="text/css"/>
<link href="https://static.melon.co.kr/static/web/resource/style/w1/l8/i/bmqlrmeyi7uljr5.css" rel="stylesheet" type="text/css"/>
<!-- 댓글 css 파일 네임 변경 -->
<!--멜론혜택 페이지 댓글 css 예외처리-->
<link href="https://static.melon.co.kr/static/web/resource/style/w1/1s/q/yjotd8rjsdw4eg.css" rel="stylesheet" type="text/css"/>
<link href="/resource/style/web/chart/melonweb_chart_4x.css" rel="stylesheet" type="text/css"/>
<link href="https://static.melon.co.kr/static/web/resource/style/w1/qa/5/rlbqwv6hljdyw.css" rel="stylesheet" type="text/css"/>
<link href="https://fonts.googleapis.com/css?family=Nunito:400" rel="stylesheet"/>
<script src="/resource/script/cds/common/web/member_api.js?_resVer=b4ce10a86ee7524c9e7d2d38ad43a769" type="text/javascript"></script>
<script src="/resource/script/cds/common/web/commerce_api.js?_resVer=3be4a69429902f23e7b988e16b9090ad" type="text/javascript"></script>
<script src="/resource/script/web/common/jquery-1.9.1.min.js" type="text/javascript"></script>
<script src="https://member.melon.com/resource/script/web/member/melonweb_member_external.js?tm=20260813" type="text/javascript"></script>
<script src="https://static.melon.co.kr/static/web/resource/script/w1/c1/d/7j9pwitvgh7.js" type="text/javascript"></script>
<script type="text/javascript">
	(function() {
		WEBPOCIMG = {
			defaultImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 500;
				var thumbType = "_500";
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_500";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noAlbum" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},

			defaultAlbumImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 500;
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_500";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noAlbum" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},

			defaultArtistImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 300;
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_300";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noArtist" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultDjImg : function(obj){
			},
			defaultMvImg : function(obj, width, height){
				if(width == null || width == '') width = $(obj).width();
				if(height == null || height == '') height = $(obj).height();

				var ratio43 = Math.floor((4/3)*10)/10;
				var ratio169 = Math.floor((16/9)*10)/10;
				var ratioObj = Math.floor((width/height)*10)/10;

				var ratio = "4x3";
				if(ratioObj == ratio43){
					ratio = "4x3"; //contentsType = "mv43";
				} else if(ratioObj == ratio169){
					ratio = "16x9"; //contentsType = "mv169";
				} else {
					if(ratioObj > 1.5) ratio = "16x9";
					else ratio = "4x3";
				}

				if(width == 0) width = 640;
				if(height == 0) ratio = "16x9";

				//가장 큰사이즈로 리사이즈함
				var thumbType = "_" + ratio + "_640";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noMovie" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultPlaylistImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 500;
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_500";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noAlbum" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultMemberImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 300;
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_300";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noArtist" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultPhotoImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 500;
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_500";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noAlbum" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultShopImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 256;
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_256";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noProduct" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultShowwingImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();

				var thumbType = "_256";
				if(width > 0 && width <= 300){
					thumbType = "_256";
				} else {
					thumbType = "_313";//추후 조절값
				}
				var altSrc = "//cdnimg.melon.co.kr/resource/image/web/default/noShowing" + thumbType + ".jpg";
				if(obj.src != altSrc){
					obj.src = altSrc;
				}
			},
			defaultTicketImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();

				var thumbType = "_256";
				if(width > 0 && width <= 300){
					thumbType = "_256";
				} else {
					thumbType = "_313";//추후 조절값
				}
				var altSrc = "//cdnimg.melon.co.kr/resource/image/web/default/noTicket" + thumbType + ".png";
				if(obj.src != altSrc){
					obj.src = altSrc;
				}
			},
			defaultSmartRadioImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noSmartradio_59_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultConcertImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noAlbum_114_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			}
		}
		,WEBELLIPSIS = {
			ellipsis : function(ellipsisName,moreClassName,eWidth){
		        //아티스트 더보기
		        var arObj = $('.' + ellipsisName);
		        for(var i = 0; i < arObj.length; i++){
		            if (arObj.eq(i).width() > eWidth ){
		                arObj.eq(i).parent().parent().parent().find('.' + moreClassName).show();
		            }
		        }
			}
		}
	})();
	</script>
</head>
<body>
<div id="wrap">
<div id="skip_nav">skip navigation
		<ul>
<li><a href="#gnb_menu">메뉴</a></li>
<li><a href="#conts_section">본문</a></li>
<li><a href="#footer">하단 정보</a></li>
</ul>
</div>
<!--  header -->
<div class="gnb2_expn" id="header">
<div class="my_fold" id="header_wrap"> <!-- 1024이상 마이영역 접었을때 클래스 my_fold 추가 -->
<div class="clfix" id="gnb">
<!-- 상단 빠른 메뉴 -->
<div id="util_menu">
<p class="none">상단 빠른 메뉴</p>
<div class="top_left">
<ul class="menu-list">
<li><a class="mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=V08&amp;ACTION_AF_CLICK=V1" href="//ticket.melon.com/main/index.htm" title="멜론티켓"><span>멜론티켓</span></a></li>
</ul>
</div>
<!-- 140603_수정 -->
<div class="top_right">
<ul class="menu-list">
<li><a class="mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=B01&amp;ACTION_AF_CLICK=V1" href="/commerce/pamphlet/web/sale_listMainView.htm" title="이용권구매"><span>이용권구매</span></a></li>
<li><a class="mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=V06&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/benefit/lounge/main.htm" title="멜론혜택"><span>멜론혜택</span></a></li>
<li><a class="mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=B03&amp;ACTION_AF_CLICK=V1" href="/event/list.htm" title="이벤트"><span>이벤트</span></a></li>
<li><a class="mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=V02&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/customer/announce/index.htm" title="공지사항"><span>공지사항</span></a></li>
</ul>
<script type="text/javascript">
							var html = '';
							var logoutReturnUrl = window.location.href;

							if(logoutReturnUrl == ''){
								logoutReturnUrl = 'www.melon.com';
							}

							if(isMelonLogin()){

								var memberKey = getMemberKey()
								var memberInfo = svcMember.displayIdByMemberKey(memberKey);
								var memberType = svcMember.getMemberType().MEMBERTYPE;
								var gradeInfo = svcMember.gradeInfoByMemberKey(memberKey);

								var memId = '';
								if(memberType == undefined || memberType == null){
									memberType = '0';
								}

								if(memberInfo.DISPLAYID != undefined || memberInfo.DISPLAYID != null){
									memId = memberInfo.DISPLAYID;
								}

								if(memId.indexOf("@") != -1 && memberType != '1'){//카카오계정이 아닌경우에만 @도메인 영역 삭제처리
									memId = memId.split("@")[0];
								}

								var fromMPS = getCookie("MPS"); // 멜론 플레이어에서 왔는지 확인.
								var fromMPSYn = fromMPS == null || fromMPS.indexOf("MELONPLAYER") < 0;

								var gradeImg = "";
								var gradeName = gradeInfo.GRADE;

								if(gradeName == undefined || gradeName == null){
									gradeName = '일반';
								}


								try {
									if(gradeName == '일반'){
										gradeImg = "";
									} else if(gradeName == 'GREEN'){
										gradeImg = "<span class=\"icon-comm grade-green\"></span>";
									} else if(gradeName == 'SILVER'){
										gradeImg = "<span class=\"icon-comm grade-silver\"></span>";
									} else if(gradeName == 'GOLD'){
										gradeImg = "<span class=\"icon-comm grade-gold\"></span>";
									} else if(gradeName == 'VIP'){
										gradeImg = "<span class=\"icon-comm grade-vip\"></span>";
									} else if(gradeName == 'MVIP'){
										gradeImg = "<span class=\"icon-comm grade-mvip\"></span>";
									}

									//카카오연동확인
									if(memberType == '1'){
										gradeImg += "<span class=\"icon-comm icon-kakao\"></span>";
									}

								} catch (e) {}

								var logoutButtonHtml = '<button type="button" title="로그아웃" class="btn_top_logout" onclick="javascript:MELON.WEBSVC.POC.logout(\'\');">로그아웃</button>';

								html = ['<div class="header_login">',
									' <span class="icon_grade">',
									'' + gradeImg + '',
									' </span>',
									' <span class="wrap_id"><a href="javascript:location.href=_getHttpsMemberDomain()+ \'/muid/web/help/myinfointro_inform.htm\';" class="user_id"><strong>' + memId + '</strong>님</a></span>',
									fromMPSYn ? logoutButtonHtml : '', //멜론 플레이어에서 로그아웃 싱크 안맞는 이슈로 인해 로그아웃 멜론 플레이어에서 왔을 시 버튼 제거
									'</div>'
								].join('');
								document.write(html);
							}
						</script>
</div>
<!-- //140603_수정 -->
</div>
<!-- //상단 빠른 메뉴 -->
<div class="header-utils">
<h1 class="logo">
<a class="mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=M01&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/index.htm" title="Melon 홈으로 이동"><span class="screen-out">Melon</span></a>
</h1>
<!-- 통합검색 영역 -->
<fieldset>
<legend>통합검색영역</legend>
<input id="top_search" name="" onkeypress="if(event.keyCode == 13){goSearch();}" placeholder="" title="검색 입력 편집창" type="text"/><input id="keywordLink" name="keywordLink" type="hidden" value=""/>
<button class="btn_icon btn_auto close" id="top_search_autocomplete_toggle" style="display: none;" title="자동검색 펼침" type="button"><span class="odd_span">자동검색 펼침</span></button> <!-- open/close 클래스 사용 -->
<button class="btn_icon search_m" title="검색" type="button"><span class="odd_span">검색</span></button>
<div class="auto_complete" id="top_search_autocomplete"><div class="auto_complete_cont" style="display:block;"><!-- 자동완성 레이어 --></div></div>
<div class="auto_complete" id="top_search_autocomplete_template" style="display: none;"> <!-- 자동완성 레이어 템플릿 -->
<!-- 텍스트 결과 -->
<ul class="text_result">
<li><a class="autocomplete-label" href="#"></a></li>
</ul>
<!-- 섬네일 결과 -->
<ul class="thumb_result">
<li class="cate"></li>
<li class="class02">
<a href="#">
<span class="thumb_40">
<span class="thumb_frame"></span>
<img alt="" class="autocomplete-img" height="40" width="40"/>
</span>
<div class="info">
<span class="autocomplete-label"></span><br/>
<span><span class="f11 autocomplete-info"></span></span>
</div>
</a>
</li>
</ul>
<!-- 검색어가 없을 때 -->
<ul class="text_result">
<li class="result_none">
<span>해당글자로 시작하는 단어가 없습니다.</span>
</li>
</ul>
</div>
</fieldset>
<form action="" id="searchFrm" method="get" style="display: none">
<input name="q" type="hidden"/>
<input name="section" type="hidden"/>
</form>
<!-- //통합검색 영역 -->
<!-- 실시간 검색어 -->
<div class="realtime_soar_keyword">
<!-- 140519_수정 -->
<a class="title" href="#none">인기 검색어</a>
<!-- //140519_수정 -->
<div class="keyword_overlay">
<ol style="overflow:hidden;">
</ol>
<!-- 140423_추가 -->
<!-- //140423_추가 -->
</div>
</div>
<!-- //실시간 검색어 -->
<!-- 배너 영역 -->
<div class="cmn_banner"></div>
</div>
</div>
<!-- 140314_gnb마크업 수정 -->
<div id="gnb_menu">
<ul>
<li class="nth1 on">
<a class="cur_menu mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=R01&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/chart/index.htm"><span class="cur_status none">현재 선택된 메뉴-</span><span class="menu_bg menu01">멜론차트</span></a>
<div class="lay_menu">
<ul>
<li class="first_child on"><a href="//www.melon.com/chart/index.htm"><span class="menu_chart m1">TOP100</span></a></li>
<li class=""><a href="//www.melon.com/chart/hot100/index.htm"><span class="menu_chart m6">HOT100</span></a></li><!-- // MELONUIT-2465 -->
<li class=""><a href="//www.melon.com/chart/day/index.htm"><span class="menu_chart m2">일간</span></a></li>
<li class=""><a href="//www.melon.com/chart/week/index.htm"><span class="menu_chart m3">주간</span></a></li>
<li class=""><a href="//www.melon.com/chart/month/index.htm"><span class="menu_chart m4">월간</span></a></li>
<li class=""><a href="//www.melon.com/chart/age/index.htm"><span class="menu_chart m5">시대</span></a></li>
</ul>
<div class="chart_finder">
<button class="btn_chart_f" onclick="location.href='//www.melon.com/chart/search/index.htm'" type="button"><span class="odd_span">차트 파인더</span></button>
</div>
</div>
</li>
<li class="nth2">
<a class="cur_menu mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=C01&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/new/index.htm"><span class="cur_status none">현재 선택된 메뉴-</span><span class="menu_bg menu02">최신음악</span></a>
<div class="lay_menu">
<ul>
<li class="first_child"><a href="//www.melon.com/new/index.htm"><span class="menu_new m1">최신곡</span></a></li>
<li class=""><a href="//www.melon.com/new/album/index.htm"><span class="menu_new m2">최신앨범</span></a></li>
<li class=""><a href="//www.melon.com/new/mv/index.htm"><span class="menu_new m3">최신 뮤직비디오</span></a></li>
</ul>
</div>
</li>
<li class="nth3">
<a class="cur_menu mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=C03&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/genre/song_list.htm?gnrCode=GN0100"><span class="cur_status none">현재 선택된 메뉴-</span><span class="menu_bg menu03">장르음악</span></a>
<div class="lay_menu">
<ul>
<li class="first_child"><a href="//www.melon.com/genre/song_list.htm?gnrCode=GN0100"><span class="menu_gnr nm1">한국대중음악</span></a></li>
<li class=""><a href="//www.melon.com/genre/song_list.htm?gnrCode=GN0900"><span class="menu_gnr nm2">해외POP음악</span></a></li>
<li class=""><a href="//www.melon.com/genre/song_list.htm?gnrCode=GN1500"><span class="menu_gnr nm3">그외 인기장르</span></a></li>
</ul>
</div>
</li>
<li class="nth4">
<a class="cur_menu mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=S04&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/dj/today/djtoday_list.htm"><span class="cur_status none">현재 선택된 메뉴-</span><span class="menu_bg menu04">멜론DJ</span></a>
<div class="lay_menu">
<ul>
<li class="first_child"><a href="//www.melon.com/dj/today/djtoday_list.htm"><span class="menu_dj m1">투데이</span></a></li>
<li class=""><a href="//www.melon.com/dj/essential/djessential_list.htm"><span class="menu_dj m2">전문가 선곡</span></a></li>
<li class=""><a href="//www.melon.com/dj/themegenre/djthemegenre_list.htm"><span class="menu_dj m3">#테마장르</span></a></li>
<li class=""><a href="//www.melon.com/dj/powerdj/djpowerdj_list.htm"><span class="menu_dj m4">파워DJ</span></a></li>
<li class=""><a href="//www.melon.com/dj/chart/djchart_list.htm"><span class="menu_dj m5">인기</span></a></li>
</ul>
</div>
</li>
<li class="nth5">
<a class="cur_menu mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=S05&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/tv/index.htm"><span class="cur_status none">현재 선택된 메뉴-</span><span class="menu_bg menu05">멜론TV</span></a>
<div class="lay_menu">
<ul>
<li class="first_child"><a href="//www.melon.com/tv/index.htm"><span class="menu_tv m1">오늘은 뭘 볼까</span></a></li>
<li class=""><a href="//www.melon.com/tv/mv/index.htm"><span class="menu_tv m2">뮤직비디오</span></a></li>
<li class=""><a href="//www.melon.com/tv/menu/index.htm?menuSeq=1"><span class="menu_tv m3">멜론 오리지널</span></a></li>
<li class=""><a href="//www.melon.com/tv/menu/index.htm?menuSeq=4"><span class="menu_tv m4">아티스트 업데이트</span></a></li>
<li class=""><a href="//www.melon.com/tv/menu/index.htm?menuSeq=3"><span class="menu_tv m5">방송</span></a></li>
</ul>
</div>
</li>
<li class="nth6">
<a class="cur_menu mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=S07&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/artistplus/todayupdate/index.htm"><span class="cur_status none">현재 선택된 메뉴-</span><span class="menu_bg menu06">스타포스트</span></a>
<div class="lay_menu">
<ul>
<li class="first_child"><a href="//www.melon.com/artistplus/todayupdate/index.htm"><span class="menu_arti m1">NOW</span></a></li>
<li class=""><a href="//www.melon.com/artistplus/artistchart/index.htm"><span class="menu_arti m3">아티스트 랭킹</span></a></li>
<li class=""><a href="//www.melon.com/artistplus/myranking/index.htm"><span class="menu_arti m4">마이 랭킹</span></a></li>
</ul>
<div class="menu_artist_btn">
<div class="artist_fan">
<button class="btn_fan" onclick="MELON.WEBSVC.POC.menu.goMyMusicFanSignArtist();" type="button"><span class="odd_span">팬맺은 아티스트</span></button>
</div>
<div class="artist_finder">

In [58]:
#User=Agent를 추가하여 방법1
url = 'https://www.melon.com/chart/'
header ={'User-agent' :'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36'}
melonResponse = requests.get(url, headers=headers) 
print(melonResponse.status_code)
soup = BeautifulSoup(melonResponse.text, 'html.parser')
soup

200

<!DOCTYPE html>

<html lang="ko">
<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<title>멜론차트&gt;TOP100&gt;멜론</title>
<meta content="음악서비스, 멜론차트, 멜론TOP100, 최신음악, 인기가요, 뮤직비디오, 앨범, 플레이어, 스트리밍, 다운로드, 아티스트플러스, 아티스트채널" name="keywords"/>
<meta content="No.1 뮤직플랫폼 멜론! 최신 트렌드부터 나를 아는 똑똑한 음악추천까지!" name="description"/>
<meta content="ee85ff6db1fa8f2226bcb671ecb2bcdbcffb6f8b" name="naver-site-verification"/>
<meta content="q4tbTQhmxa4La3OdNLsNOCxrJ_WV6lUlBFrFW4-HqQc" name="google-site-verification"/>
<meta content="4022717807957185" property="fb:app_id"/>
<meta content="Melon" property="og:title"/>
<meta content="https://cdnimg.melon.co.kr/resource/image/web/common/logo_melon142x99.png" property="og:image"/>
<meta content="음악이 필요한 순간, 멜론" property="og:description"/>
<meta content="http://www.melon.com/chart/" property="og:url"/>
<meta content="website" property="og:type"/>
<meta content="멜론" property="og:site_name"/>
<meta content="width=device-width" name="viewport"/>
<link href="/favicon.ico?2" id="favicon" rel="shortcut icon" type="image/x-icon"/>
<link href="/resource/style/web/common/melonweb_layout.css?tm=20260604" rel="stylesheet" type="text/css"/>
<link href="https://static.melon.co.kr/static/web/resource/style/w1/l8/i/bmqlrmeyi7uljr5.css" rel="stylesheet" type="text/css"/>
<!-- 댓글 css 파일 네임 변경 -->
<!--멜론혜택 페이지 댓글 css 예외처리-->
<link href="https://static.melon.co.kr/static/web/resource/style/w1/1s/q/yjotd8rjsdw4eg.css" rel="stylesheet" type="text/css"/>
<link href="/resource/style/web/chart/melonweb_chart_4x.css" rel="stylesheet" type="text/css"/>
<link href="https://static.melon.co.kr/static/web/resource/style/w1/qa/5/rlbqwv6hljdyw.css" rel="stylesheet" type="text/css"/>
<link href="https://fonts.googleapis.com/css?family=Nunito:400" rel="stylesheet"/>
<script src="/resource/script/cds/common/web/member_api.js?_resVer=b4ce10a86ee7524c9e7d2d38ad43a769" type="text/javascript"></script>
<script src="/resource/script/cds/common/web/commerce_api.js?_resVer=3be4a69429902f23e7b988e16b9090ad" type="text/javascript"></script>
<script src="/resource/script/web/common/jquery-1.9.1.min.js" type="text/javascript"></script>
<script src="https://member.melon.com/resource/script/web/member/melonweb_member_external.js?tm=20260813" type="text/javascript"></script>
<script src="https://static.melon.co.kr/static/web/resource/script/w1/c1/d/7j9pwitvgh7.js" type="text/javascript"></script>
<script type="text/javascript">
	(function() {
		WEBPOCIMG = {
			defaultImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 500;
				var thumbType = "_500";
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_500";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noAlbum" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},

			defaultAlbumImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 500;
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_500";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noAlbum" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},

			defaultArtistImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 300;
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_300";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noArtist" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultDjImg : function(obj){
			},
			defaultMvImg : function(obj, width, height){
				if(width == null || width == '') width = $(obj).width();
				if(height == null || height == '') height = $(obj).height();

				var ratio43 = Math.floor((4/3)*10)/10;
				var ratio169 = Math.floor((16/9)*10)/10;
				var ratioObj = Math.floor((width/height)*10)/10;

				var ratio = "4x3";
				if(ratioObj == ratio43){
					ratio = "4x3"; //contentsType = "mv43";
				} else if(ratioObj == ratio169){
					ratio = "16x9"; //contentsType = "mv169";
				} else {
					if(ratioObj > 1.5) ratio = "16x9";
					else ratio = "4x3";
				}

				if(width == 0) width = 640;
				if(height == 0) ratio = "16x9";

				//가장 큰사이즈로 리사이즈함
				var thumbType = "_" + ratio + "_640";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noMovie" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultPlaylistImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 500;
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_500";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noAlbum" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultMemberImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 300;
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_300";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noArtist" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultPhotoImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 500;
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_500";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noAlbum" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultShopImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 256;
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_256";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noProduct" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultShowwingImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();

				var thumbType = "_256";
				if(width > 0 && width <= 300){
					thumbType = "_256";
				} else {
					thumbType = "_313";//추후 조절값
				}
				var altSrc = "//cdnimg.melon.co.kr/resource/image/web/default/noShowing" + thumbType + ".jpg";
				if(obj.src != altSrc){
					obj.src = altSrc;
				}
			},
			defaultTicketImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();

				var thumbType = "_256";
				if(width > 0 && width <= 300){
					thumbType = "_256";
				} else {
					thumbType = "_313";//추후 조절값
				}
				var altSrc = "//cdnimg.melon.co.kr/resource/image/web/default/noTicket" + thumbType + ".png";
				if(obj.src != altSrc){
					obj.src = altSrc;
				}
			},
			defaultSmartRadioImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noSmartradio_59_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultConcertImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noAlbum_114_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			}
		}
		,WEBELLIPSIS = {
			ellipsis : function(ellipsisName,moreClassName,eWidth){
		        //아티스트 더보기
		        var arObj = $('.' + ellipsisName);
		        for(var i = 0; i < arObj.length; i++){
		            if (arObj.eq(i).width() > eWidth ){
		                arObj.eq(i).parent().parent().parent().find('.' + moreClassName).show();
		            }
		        }
			}
		}
	})();
	</script>
</head>
<body>
<div id="wrap">
<div id="skip_nav">skip navigation
		<ul>
<li><a href="#gnb_menu">메뉴</a></li>
<li><a href="#conts_section">본문</a></li>
<li><a href="#footer">하단 정보</a></li>
</ul>
</div>
<!--  header -->
<div class="gnb2_expn" id="header">
<div class="my_fold" id="header_wrap"> <!-- 1024이상 마이영역 접었을때 클래스 my_fold 추가 -->
<div class="clfix" id="gnb">
<!-- 상단 빠른 메뉴 -->
<div id="util_menu">
<p class="none">상단 빠른 메뉴</p>
<div class="top_left">
<ul class="menu-list">
<li><a class="mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=V08&amp;ACTION_AF_CLICK=V1" href="//ticket.melon.com/main/index.htm" title="멜론티켓"><span>멜론티켓</span></a></li>
</ul>
</div>
<!-- 140603_수정 -->
<div class="top_right">
<ul class="menu-list">
<li><a class="mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=B01&amp;ACTION_AF_CLICK=V1" href="/commerce/pamphlet/web/sale_listMainView.htm" title="이용권구매"><span>이용권구매</span></a></li>
<li><a class="mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=V06&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/benefit/lounge/main.htm" title="멜론혜택"><span>멜론혜택</span></a></li>
<li><a class="mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=B03&amp;ACTION_AF_CLICK=V1" href="/event/list.htm" title="이벤트"><span>이벤트</span></a></li>
<li><a class="mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=V02&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/customer/announce/index.htm" title="공지사항"><span>공지사항</span></a></li>
</ul>
<script type="text/javascript">
							var html = '';
							var logoutReturnUrl = window.location.href;

							if(logoutReturnUrl == ''){
								logoutReturnUrl = 'www.melon.com';
							}

							if(isMelonLogin()){

								var memberKey = getMemberKey()
								var memberInfo = svcMember.displayIdByMemberKey(memberKey);
								var memberType = svcMember.getMemberType().MEMBERTYPE;
								var gradeInfo = svcMember.gradeInfoByMemberKey(memberKey);

								var memId = '';
								if(memberType == undefined || memberType == null){
									memberType = '0';
								}

								if(memberInfo.DISPLAYID != undefined || memberInfo.DISPLAYID != null){
									memId = memberInfo.DISPLAYID;
								}

								if(memId.indexOf("@") != -1 && memberType != '1'){//카카오계정이 아닌경우에만 @도메인 영역 삭제처리
									memId = memId.split("@")[0];
								}

								var fromMPS = getCookie("MPS"); // 멜론 플레이어에서 왔는지 확인.
								var fromMPSYn = fromMPS == null || fromMPS.indexOf("MELONPLAYER") < 0;

								var gradeImg = "";
								var gradeName = gradeInfo.GRADE;

								if(gradeName == undefined || gradeName == null){
									gradeName = '일반';
								}


								try {
									if(gradeName == '일반'){
										gradeImg = "";
									} else if(gradeName == 'GREEN'){
										gradeImg = "<span class=\"icon-comm grade-green\"></span>";
									} else if(gradeName == 'SILVER'){
										gradeImg = "<span class=\"icon-comm grade-silver\"></span>";
									} else if(gradeName == 'GOLD'){
										gradeImg = "<span class=\"icon-comm grade-gold\"></span>";
									} else if(gradeName == 'VIP'){
										gradeImg = "<span class=\"icon-comm grade-vip\"></span>";
									} else if(gradeName == 'MVIP'){
										gradeImg = "<span class=\"icon-comm grade-mvip\"></span>";
									}

									//카카오연동확인
									if(memberType == '1'){
										gradeImg += "<span class=\"icon-comm icon-kakao\"></span>";
									}

								} catch (e) {}

								var logoutButtonHtml = '<button type="button" title="로그아웃" class="btn_top_logout" onclick="javascript:MELON.WEBSVC.POC.logout(\'\');">로그아웃</button>';

								html = ['<div class="header_login">',
									' <span class="icon_grade">',
									'' + gradeImg + '',
									' </span>',
									' <span class="wrap_id"><a href="javascript:location.href=_getHttpsMemberDomain()+ \'/muid/web/help/myinfointro_inform.htm\';" class="user_id"><strong>' + memId + '</strong>님</a></span>',
									fromMPSYn ? logoutButtonHtml : '', //멜론 플레이어에서 로그아웃 싱크 안맞는 이슈로 인해 로그아웃 멜론 플레이어에서 왔을 시 버튼 제거
									'</div>'
								].join('');
								document.write(html);
							}
						</script>
</div>
<!-- //140603_수정 -->
</div>
<!-- //상단 빠른 메뉴 -->
<div class="header-utils">
<h1 class="logo">
<a class="mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=M01&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/index.htm" title="Melon 홈으로 이동"><span class="screen-out">Melon</span></a>
</h1>
<!-- 통합검색 영역 -->
<fieldset>
<legend>통합검색영역</legend>
<input id="top_search" name="" onkeypress="if(event.keyCode == 13){goSearch();}" placeholder="" title="검색 입력 편집창" type="text"/><input id="keywordLink" name="keywordLink" type="hidden" value=""/>
<button class="btn_icon btn_auto close" id="top_search_autocomplete_toggle" style="display: none;" title="자동검색 펼침" type="button"><span class="odd_span">자동검색 펼침</span></button> <!-- open/close 클래스 사용 -->
<button class="btn_icon search_m" title="검색" type="button"><span class="odd_span">검색</span></button>
<div class="auto_complete" id="top_search_autocomplete"><div class="auto_complete_cont" style="display:block;"><!-- 자동완성 레이어 --></div></div>
<div class="auto_complete" id="top_search_autocomplete_template" style="display: none;"> <!-- 자동완성 레이어 템플릿 -->
<!-- 텍스트 결과 -->
<ul class="text_result">
<li><a class="autocomplete-label" href="#"></a></li>
</ul>
<!-- 섬네일 결과 -->
<ul class="thumb_result">
<li class="cate"></li>
<li class="class02">
<a href="#">
<span class="thumb_40">
<span class="thumb_frame"></span>
<img alt="" class="autocomplete-img" height="40" width="40"/>
</span>
<div class="info">
<span class="autocomplete-label"></span><br/>
<span><span class="f11 autocomplete-info"></span></span>
</div>
</a>
</li>
</ul>
<!-- 검색어가 없을 때 -->
<ul class="text_result">
<li class="result_none">
<span>해당글자로 시작하는 단어가 없습니다.</span>
</li>
</ul>
</div>
</fieldset>
<form action="" id="searchFrm" method="get" style="display: none">
<input name="q" type="hidden"/>
<input name="section" type="hidden"/>
</form>
<!-- //통합검색 영역 -->
<!-- 실시간 검색어 -->
<div class="realtime_soar_keyword">
<!-- 140519_수정 -->
<a class="title" href="#none">인기 검색어</a>
<!-- //140519_수정 -->
<div class="keyword_overlay">
<ol style="overflow:hidden;">
</ol>
<!-- 140423_추가 -->
<!-- //140423_추가 -->
</div>
</div>
<!-- //실시간 검색어 -->
<!-- 배너 영역 -->
<div class="cmn_banner"></div>
</div>
</div>
<!-- 140314_gnb마크업 수정 -->
<div id="gnb_menu">
<ul>
<li class="nth1 on">
<a class="cur_menu mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=R01&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/chart/index.htm"><span class="cur_status none">현재 선택된 메뉴-</span><span class="menu_bg menu01">멜론차트</span></a>
<div class="lay_menu">
<ul>
<li class="first_child on"><a href="//www.melon.com/chart/index.htm"><span class="menu_chart m1">TOP100</span></a></li>
<li class=""><a href="//www.melon.com/chart/hot100/index.htm"><span class="menu_chart m6">HOT100</span></a></li><!-- // MELONUIT-2465 -->
<li class=""><a href="//www.melon.com/chart/day/index.htm"><span class="menu_chart m2">일간</span></a></li>
<li class=""><a href="//www.melon.com/chart/week/index.htm"><span class="menu_chart m3">주간</span></a></li>
<li class=""><a href="//www.melon.com/chart/month/index.htm"><span class="menu_chart m4">월간</span></a></li>
<li class=""><a href="//www.melon.com/chart/age/index.htm"><span class="menu_chart m5">시대</span></a></li>
</ul>
<div class="chart_finder">
<button class="btn_chart_f" onclick="location.href='//www.melon.com/chart/search/index.htm'" type="button"><span class="odd_span">차트 파인더</span></button>
</div>
</div>
</li>
<li class="nth2">
<a class="cur_menu mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=C01&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/new/index.htm"><span class="cur_status none">현재 선택된 메뉴-</span><span class="menu_bg menu02">최신음악</span></a>
<div class="lay_menu">
<ul>
<li class="first_child"><a href="//www.melon.com/new/index.htm"><span class="menu_new m1">최신곡</span></a></li>
<li class=""><a href="//www.melon.com/new/album/index.htm"><span class="menu_new m2">최신앨범</span></a></li>
<li class=""><a href="//www.melon.com/new/mv/index.htm"><span class="menu_new m3">최신 뮤직비디오</span></a></li>
</ul>
</div>
</li>
<li class="nth3">
<a class="cur_menu mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=C03&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/genre/song_list.htm?gnrCode=GN0100"><span class="cur_status none">현재 선택된 메뉴-</span><span class="menu_bg menu03">장르음악</span></a>
<div class="lay_menu">
<ul>
<li class="first_child"><a href="//www.melon.com/genre/song_list.htm?gnrCode=GN0100"><span class="menu_gnr nm1">한국대중음악</span></a></li>
<li class=""><a href="//www.melon.com/genre/song_list.htm?gnrCode=GN0900"><span class="menu_gnr nm2">해외POP음악</span></a></li>
<li class=""><a href="//www.melon.com/genre/song_list.htm?gnrCode=GN1500"><span class="menu_gnr nm3">그외 인기장르</span></a></li>
</ul>
</div>
</li>
<li class="nth4">
<a class="cur_menu mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=S04&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/dj/today/djtoday_list.htm"><span class="cur_status none">현재 선택된 메뉴-</span><span class="menu_bg menu04">멜론DJ</span></a>
<div class="lay_menu">
<ul>
<li class="first_child"><a href="//www.melon.com/dj/today/djtoday_list.htm"><span class="menu_dj m1">투데이</span></a></li>
<li class=""><a href="//www.melon.com/dj/essential/djessential_list.htm"><span class="menu_dj m2">전문가 선곡</span></a></li>
<li class=""><a href="//www.melon.com/dj/themegenre/djthemegenre_list.htm"><span class="menu_dj m3">#테마장르</span></a></li>
<li class=""><a href="//www.melon.com/dj/powerdj/djpowerdj_list.htm"><span class="menu_dj m4">파워DJ</span></a></li>
<li class=""><a href="//www.melon.com/dj/chart/djchart_list.htm"><span class="menu_dj m5">인기</span></a></li>
</ul>
</div>
</li>
<li class="nth5">
<a class="cur_menu mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=S05&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/tv/index.htm"><span class="cur_status none">현재 선택된 메뉴-</span><span class="menu_bg menu05">멜론TV</span></a>
<div class="lay_menu">
<ul>
<li class="first_child"><a href="//www.melon.com/tv/index.htm"><span class="menu_tv m1">오늘은 뭘 볼까</span></a></li>
<li class=""><a href="//www.melon.com/tv/mv/index.htm"><span class="menu_tv m2">뮤직비디오</span></a></li>
<li class=""><a href="//www.melon.com/tv/menu/index.htm?menuSeq=1"><span class="menu_tv m3">멜론 오리지널</span></a></li>
<li class=""><a href="//www.melon.com/tv/menu/index.htm?menuSeq=4"><span class="menu_tv m4">아티스트 업데이트</span></a></li>
<li class=""><a href="//www.melon.com/tv/menu/index.htm?menuSeq=3"><span class="menu_tv m5">방송</span></a></li>
</ul>
</div>
</li>
<li class="nth6">
<a class="cur_menu mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=S07&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/artistplus/todayupdate/index.htm"><span class="cur_status none">현재 선택된 메뉴-</span><span class="menu_bg menu06">스타포스트</span></a>
<div class="lay_menu">
<ul>
<li class="first_child"><a href="//www.melon.com/artistplus/todayupdate/index.htm"><span class="menu_arti m1">NOW</span></a></li>
<li class=""><a href="//www.melon.com/artistplus/artistchart/index.htm"><span class="menu_arti m3">아티스트 랭킹</span></a></li>
<li class=""><a href="//www.melon.com/artistplus/myranking/index.htm"><span class="menu_arti m4">마이 랭킹</span></a></li>
</ul>
<div class="menu_artist_btn">
<div class="artist_fan">
<button class="btn_fan" onclick="MELON.WEBSVC.POC.menu.goMyMusicFanSignArtist();" type="button"><span class="odd_span">팬맺은 아티스트</span></button>
</div>
<div class="artist_finder">

In [ ]:
#1위 : LOVE ATTACK | RESCENE (리센느)의 url{}
#순위, 곡명, 가수, 페이지

In [91]:
#1위:    div.wrap.t_center > span.rank
rank_els =soup.select('div.wrap.t_center > span.rank')[1:]
ranks=[rank.text for rank in rank_els]

In [88]:
# 노래제목
#div.ellipsis.rank01 > span > a
title_els = soup.select('div.ellipsis.rank01 > span > a')
titles=[titles.text for titles in title_els]

In [89]:
# 가수명   한곡에 가수 둘셋으로 등록되어 select로 사용시 문제됨
# span.checkEllipsis
singer_els = soup.select('span.checkEllipsis')
singers=[singer.text.replace('\xa0','') for singer in singer_els]

links=[]
for singer_el in singer_els:
    singer_link='https://www.melon.com/'+singer_el.find('a').attrs.get('href')
    links.append(singer_link)

In [102]:
# for idx, (title, singer, link) in enumerate(zip(titles,singers,links)):
#     print(f"{idx+1}위.{title}|{singer}")
melon_chart_list=[]
for rank, title, singer, link in zip(ranks,titles,singers,links):
    melon_chart_list.append({
        '순위':rank,
        '곡명':title,
        '가수':singer,
        '가수페이지':link
    })
pd.DataFrame(melon_chart_list)

,순위,곡명,가수,가수페이지
0,1,LOVE ATTACK,RESCENE(리센느),https://www.melon.com//artist/detail.htm?artis...
1,2,갑자기,아이오아이(I.O.I),https://www.melon.com//artist/detail.htm?artis...
2,3,REDRED,CORTIS(코르티스),https://www.melon.com//artist/detail.htm?artis...
3,4,LEMONADE,aespa,https://www.melon.com//artist/detail.htm?artis...
4,5,Pretty Girl,RESCENE(리센느),https://www.melon.com//artist/detail.htm?artis...
...,...,...,...,...
95,96,BLACKHOLE,IVE(아이브),https://www.melon.com//artist/detail.htm?artis...
96,97,FOCUS,Hearts2Hearts(하츠투하츠),https://www.melon.com//artist/detail.htm?artis...
97,98,Soda Pop,"KPopDemonHuntersCast, DannyChung, SajaBoys, An...",https://www.melon.com//artist/detail.htm?artis...
98,99,OVERDRIVE,TWS(투어스),https://www.melon.com//artist/detail.htm?artis...
99,100,2.0,방탄소년단,https://www.melon.com//artist/detail.htm?artis...

### 5) 네이버 지식인 검색(open API 사용x)
 - 특정 keyword를 특정 페이지 수만큼

In [108]:
#방법1
from requests import get
from bs4 import BeautifulSoup
keyword = '클로드'
url = f'https://kin.naver.com/search/list.naver?query={keyword}'
print(url)
response = get(url)
print(response.status_code)
soup=BeautifulSoup(response.text,'html.parser')

https://kin.naver.com/search/list.naver?query=%ED%81%B4%EB%A1%9C%EB%93%9C
200

In [110]:
##방법2
from urllib.request import urlopen
from bs4 import BeautifulSoup
from urllib.parse import quote
keyword = quote('클로드')
url = f'https://kin.naver.com/search/list.naver?query={keyword}'
response=urlopen(url)
soup=BeautifulSoup(response,'html.parser')

In [126]:
# keyword를 원하는 페이지 수만큼
#방법1
from requests import get
from bs4 import BeautifulSoup
keyword = '클로드'
page = 2
item_list=[] # 크롤링한 데이터를 담을 list
for page in range(1,page+1):
    url= f'https://kin.naver.com/search/list.naver?query={keyword}&page={page}'
    #print(url)
    response = get(url)
    #print(response.status_code)
    soup=BeautifulSoup(response.text,'html.parser')
    #글제목, link
    dt_els=soup.find_all('dt')
    for dt_el in dt_els:
        item =dt_el.find('a')
        item_list.append({
            'title':item.text,
            'link':item.attrs.get('href')
        })
df=pd.DataFrame(item_list)

In [129]:
df.head()

,title,link
0,클로드 캔바 연동 오류,https://kin.naver.com/qna/detail.naver?dirId=1...
1,클로드 프로,https://kin.naver.com/qna/detail.naver?dirId=1...
2,클로드 나이인증,https://kin.naver.com/qna/detail.naver?dirId=1...
3,"클로드 AI의 오류, 왜곡, 문제점, 한계점들은?",https://kin.naver.com/qna/detail.naver?dirId=1...
4,"클로드 AI, 기업에서 많이 쓰는 이유가 뭘까요....",https://kin.naver.com/qna/detail.naver?dirId=1...

## 2.2 open API사용: json웹데이터 수집
### 1) 네이버 지식으로 검색(open API사용 0)

- 네이버개발자세넡에서 애플리케이션을 등록(id, pw) => NAVER API HUB

In [130]:
%pip install dotenv

Collecting dotenv
  Downloading dotenv-0.9.9-py2.py3-none-any.whl (1.9 kB)
Collecting python-dotenv
  Downloading python_dotenv-1.2.2-py3-none-any.whl (22 kB)
Installing collected packages: python-dotenv, dotenv
Successfully installed dotenv-0.9.9 python-dotenv-1.2.2
Note: you may need to restart the kernel to use updated packages.

In [133]:
# 환경변수를 쓰기 위한 패키지 : dotenv
from dotenv import load_dotenv
import os
load_dotenv(
            #dotenv_path='.env'
)
print(os.getenv('CLIENT_ID')[:3])
print(os.getenv('CLIENT_SECRET')[:3])

SkN
Kwk

In [146]:

# 방법2
import os
import sys
import urllib.request
import json
client_id = os.getenv('CLIENT_ID')
client_secret = os.getenv('CLIENT_SECRET')
encText = urllib.parse.quote("쳇지피티")
url = f"https://openapi.naver.com/v1/search/kin.json?query={encText}" # JSON 결과
# request = urllib.request.Request(url)
# request.add_header("X-Naver-Client-Id",client_id)
# request.add_header("X-Naver-Client-Secret",client_secret)
headers = {
    'X-Naver-Client-Id': client_id,
    'X-Naver-Client-Secret':client_secret
}
request = urllib.request.Request(url, headers=headers)
response = urllib.request.urlopen(request)
rescode = response.getcode()
if(rescode==200):
    response_body = response.read()
    #print(response_body.decode('utf-8')[:30])
else:
    print("Error Code:" + rescode)

data = json.loads(response_body) # 문자를 json형태로 변환
print('data의 응답들:',data.keys())
print('검색결과 갯수:',len(data['items']))

items=data['items']
items_list=[]
for item in items:
   # print(item)
    title=item['title'].replace('<b>','').replace('</b>','')
    link=item['link']
    description=item['description'].replace('<b>','').replace('</b>','')
    items_list.append([title, link, description])
pd.DataFrame(items_list, columns=['title','link','description'])

data의 응답들: dict_keys(['lastBuildDate', 'total', 'start', 'display', 'items'])
검색결과 갯수: 10

,title,link,description
0,박사논문을 잘 쓰려면 쳇지피티 외 어떤ai하나더 추천해줘요,https://kin.naver.com/qna/detail.naver?dirId=4...,박사논문을 잘 쓰려면 쳇지피티 외 어떤ai하나더 추천해줘요. 논문제목 작성 및 논문...
1,쳇지피티 오류 나만 그래요?,https://kin.naver.com/qna/detail.naver?dirId=1...,짜증나네 삭제해도 안되고 왜이러는거에요 현재 쳇지피티 오류 나는거 모두 다 동일한 ...
2,쳇지피티로 사주 해석을 해봤는데 맞는건가요?,https://kin.naver.com/qna/detail.naver?dirId=3...,쳇지피티로 배우자가 어떤 사람인지 사주 해석을 해봤는데 맞는건가요??? 전체 흐름을...
3,박사논문을 잘 쓰려면 쳇지피티 외 어떤ai하나더 추천해줘요,https://kin.naver.com/qna/detail.naver?dirId=4...,박사논문을 잘 쓰려면 쳇지피티 외 어떤ai하나더 추천해줘요. 논문제목 작성 및 논문...
4,고등학교 수행평가에 쳇지피티 쓰면 안되나요?,https://kin.naver.com/qna/detail.naver?dirId=1...,쳇지피티로 쓰던데 쓰면 안되아요? 요즘 지피티 검사기도 있고 선생님들도 지피티쓴 글...
5,카카오톡 쳇지피티,https://kin.naver.com/qna/detail.naver?dirId=1...,이거 사용하는거 무료인가요 ? 돈 나가요!
6,쳇지피티 오류,https://kin.naver.com/qna/detail.naver?dirId=1...,이거 왜이런건가요…? 한번에 너무 많은 요구를 했거나 해당 버전을 동시간대에 사용하...
7,뉴스 보다가 범죄자가 검색한 쳇 지피티 도 조회 한다고 하....,https://kin.naver.com/qna/detail.naver?dirId=6...,제미나이 이런것도 포렌식 해서 다 검열을 하나요 첨 알아서요 검색 목록만 보는줄 알...
8,쳇 지피티 운세 정확한가요?,https://kin.naver.com/qna/detail.naver?dirId=3...,쳇 지피티 운세 어느정도 정확한가요? 무료로 꽤 정확한 운세 보는 방법 있으면 알려...
9,쳇지피티로 사주 해석을 해봤는데 맞는건가요?,https://kin.naver.com/qna/detail.naver?dirId=3...,쳇지피티로 배우자가 어떤 사람인지 사주 해석을 해봤는데 맞는건가요??? 안녕하세요 ...

In [9]:
#방법1
import os
from requests import get
import json
import pandas as pd
client_id = os.getenv('CLIENT_ID')
client_secret = os.getenv('CLIENT_SECRET')
encText = "클로드"
url = f"https://openapi.naver.com/v1/search/kin.json" # JSON 결과
params = {'query':encText,'display':20}
headers = {
    'X-Naver-Client-Id': client_id,
    'X-Naver-Client-Secret':client_secret
}
response =requests.get(url,params=params, headers=headers)
# print('response 상태: ',response.status_code)
# print(response.text[:30])
#data = json.loads(response_body) # 문자를 json형태로 변환
items=response.json()['items']#json
items_list=[]
for item in items:
   # print(item)
    title=item['title'].replace('<b>','').replace('</b>','')
    link=item['link']
    description=item['description'].replace('<b>','').replace('</b>','')
    items_list.append([title, link, description])
pd.DataFrame(items_list, columns=['title','link','description']).sample()

,title,link,description
0,바이브코딩 입문 책으로 클로드 코드 시작해도 될까요?,https://kin.naver.com/qna/detail.naver?dirId=3...,"요즘 코딩에 관심이 생겨서 이것저것 알아보는 중인데요, 특히 클로드 코드라는 게 핫..."

### NAVEHUB 방식으로 지식IN 검색

In [7]:
#방법1
import os
import requests 
import json
import pandas as pd
from dotenv import load_dotenv
load_dotenv() #환경 변수 load
client_id = os.getenv('NEW_CLIENT_ID')
client_secret = os.getenv('NEW_CLIENT_SECRET')
encText = "카카오톡"
url = f"https://naverapihub.apigw.ntruss.com/search/v1/kin" # JSON 결과
params = {'query':encText,'display':20}
headers = {
    'X-NCP-APIGW-API-KEY-ID': client_id,
    'X-NCP-APIGW-API-KEY':client_secret
}
response =requests.get(url,params=params, headers=headers)
# print('response 상태: ',response.status_code)
# print(response.text[:30])
#data = json.loads(response_body) # 문자를 json형태로 변환
items=response.json()['items']#json
items_list=[]
for item in items:
   # print(item)d
    title=item['title'].replace('<b>','').replace('</b>','')
    link=item['link']
    description=item['description'].replace('<b>','').replace('</b>','')
    items_list.append([title, link, description])
pd.DataFrame(items_list, columns=['title','link','description']).sample()

,title,link,description
5,카카오톡 여러 기기에서 로그인,https://kin.naver.com/qna/detail.naver?dirId=1...,원래 카카오톡을 핸드폰 + 아이패드 + 컴퓨터 이렇게 세개에서 쓸땐 문제가 없었는데...

In [4]:
%pip install dotenv

Requirement already satisfied: dotenv in c:\users\mbc\anaconda3\lib\site-packages (0.9.9)
Requirement already satisfied: python-dotenv in c:\users\mbc\anaconda3\lib\site-packages (from dotenv) (1.2.2)
Note: you may need to restart the kernel to use updated packages.

In [10]:
import os
import requests
from requests import get
import json
import pandas as pd
client_id = os.getenv('CLIENT_ID')
client_secret = os.getenv('CLIENT_SECRET')
encText="데님"
url= f"https://openapi.naver.com/v1/search/image"
params = {'query':encText,'display':20}
headers = {
    'X-Naver-Client-Id': client_id,
    'X-Naver-Client-Secret':client_secret
}
response =requests.get(url,params=params, headers=headers)
items=response.json()['items']#json
items_list=[]
for item in items:
    title=item['title'].replace('<b>','').replace('</b>','')
    link=item['link']
    thumbnail=item['thumbnail']
    sizeheight=item['sizeheight']
    sizewidth=item['sizewidth']
    items_list.append([title, link, thumbnail, sizeheight, sizewidth])
df=pd.DataFrame(items_list,columns=['title','link','thumbnail','sizeheight','sizewidth'])
df.to_csv('data/denim_file.csv',index=False)

http://shopping.phinf.naver.net/main_5337646/53376469522.20250305194756.jpg
https://search.pstatic.net/common/?type=b150&src=http%3A%2F%2Fshopping.phinf.naver.net%2Fmain_5337646%2F53376469522.20250305194756.jpg

In [ ]:
##함수로 방법1
def get_image_list(query):
    'query로 검색한 이미지 정보(제목, 링크,썸네일, size) 100건 데이터 프레임을 return(방법1)'
    from dotenv import load_dotenv
    import os
    import requests
    import pandas as pd
    load_dotenv()
    client_id = os.getenv('CLIENT_ID')
    client_secret = os.getenv('CLIENT_SECRET')
    headers = {
        'X-Naver-Client-Id': client_id,
        'X-Naver-Client-Secret':client_secret
    }
    url = 'https://openapi.naver.com/v1/search/image'
    params = {'query':query, 'display':100 }
    response = requests.get(url, params=params, headers=headers)
    
    items = response.json()['items']
    # print(items[:2])
    items_list = []
    for item in items:
        items_list.append({
            '제목':item.get('title'),
            '링크':item.get('link'),
            '썸네일':item.get('thumbnail'),
            'sizeheight':item.get('sizeheight'),
            'sizewidth':item.get('sizewidth')
        })
    return pd.DataFrame(items_list)
get_image_list("청바지")

In [15]:
##함수로 방법2
def get_image_list(query):
    'query로 검색한 이미지 정보(제목, 링크,썸네일, size) 100건 데이터 프레임을 return(방법2)'
    from dotenv import load_dotenv
    import os
    from urllib.request import urlopen, Request
    from urllib.parse import quote
    import json
    import pandas as pd
    load_dotenv()
    client_id = os.getenv('CLIENT_ID')
    client_secret = os.getenv('CLIENT_SECRET')
    headers = {
        'X-Naver-Client-Id': client_id,
        'X-Naver-Client-Secret':client_secret
    }
    query = quote(query)
    url = f'https://openapi.naver.com/v1/search/image?query={query}&display=100'
    request = Request(url, headers=headers)
    response = urlopen(request)
    
    items = json.loads(response.read())['items']
    # print(items[:2])
    items_list = []
    for item in items:
        items_list.append({
            '제목':item.get('title'),
            '링크':item.get('link'),
            '썸네일':item.get('thumbnail'),
            'sizeheight':item.get('sizeheight'),
            'sizewidth':item.get('sizewidth')
        })
    return pd.DataFrame(items_list)
df = get_image_list("청바지")
df.sample()

,제목,링크,썸네일,sizeheight,sizewidth
31,포인트 와이드 청바지 (1color) : 런인,http://shop1.phinf.naver.net/20220914_29/16631...,https://search.pstatic.net/common/?type=b150&s...,1514,1514

In [22]:
#df에 있는 이미지 로컬에 저장하기
print(df.loc[0,'링크']) #메인_00_데님.jpg
print(df.loc[0,'썸네일']) #썸네일_00_데님.jpg

https://thumbnail.10x10.co.kr/webimage/image/basic600/741/B007415375.jpg?cmd=thumb&w=500&h=500&fit=true&ws=false
https://search.pstatic.net/sunny/?type=b150&src=https%3A%2F%2Fthumbnail.10x10.co.kr%2Fwebimage%2Fimage%2Fbasic600%2F741%2FB007415375.jpg%3Fcmd%3Dthumb%26w%3D500%26h%3D500%26fit%3Dtrue%26ws%3Dfalse

In [36]:
 url='11.jpg'
# '.'+url.split('.')[-1] # 잘안쓰는 방법
url.rfind('.')

2

In [42]:
def save_image(attr, idx, link, query):
    'link의 이미지를 image/attr_idx_query.확장자로 local에 저장'
    import requests, os
    from urllib.parse import urlparse
    response =requests.get(link)
    content_type = response.headers.get('Content-Type','')
    #print(content_type) #image/jpeg
    
    # link에서 확장자(jpg) 추출
    #file_extension = link.split('.')[-1]
    file_extension = link[link.rfind('.'):]
    # 확장자 뒤에 ?가 있는 위치(?가 없으면 -1)
    index= file_extension.find('?') 
    if index != -1:
        file_extension=file_extension[:index]
    # 확장자 뒤에 %가 있는 위치(?가 없으면 -1)    
    index= file_extension.find('%')
    if index != -1:
        file_extension=file_extension[:index]
    # 허용할 이미지 확장자 인지 
    valid_extension = ['.jpg', '.jpeg', '.png', '.gif', '.bmp','.webp']
    if file_extension.lower() not in valid_extension:
        # 허용할 이미지 확장자가 아닌경우(ex: .net)
        print(f'{idx}번째{attr}의 url에서 확장자를 추출 못하여 header에서 도전해봄')
        content_type = response.headers.get('Content-Type','') # image/jpeg
        file_extension = content_type.split('image/')[-1]
        file_extension = file_extension.replace('jpeg','jpg')
        file_extension = file_extension if file_extension in valid_extension else 'jpg'
    # image 폴더가 없으면 image 폴더새성
    save_dir ='image'
    os.makedirs(save_dir,exist_ok=True)
    #이미지 저장
    with open(f'{save_dir}/{attr}_{idx:02}_{query}.{file_extension}','wb') as f :
        f.write(response.content) #파일저장
    
    
    
#     index = file_extension.find('?') #확장자 뒤에 ?가 있는 위치(?가 없으면 -1)   
#     if index !=-1:
#         file_extension = file_extension[:quote_index] # 물음표 앞까지만 확장자로
#     img= requests.get(link).content
#     with open(f'image/{attr}_{idx:02}_{query}.{file_extension}','wb') as f:
#         f.write(img) #파일저장
save_image('메인',0,df.loc[0,'링크'], '청바지')

### naver api 요청받아 이미지제목, link, 썸네일link, 정보를 csv로 백업, 이미지 link와 썸네일link 이미지를 다운

In [45]:
##함수로 방법2
def get_image_list_save_file(query):
    '''
    naver api 요청받아 이미지제목, link, 썸네일link, 정보를 데이터프레임으로 return
    데이터프레임을 csv로 백업, 
    이미지 link와 썸네일link 이미지를 다운(방법2)
    '''
    from dotenv import load_dotenv
    import os
    from urllib.request import urlopen, Request
    from urllib.parse import quote
    import json
    import pandas as pd
    load_dotenv(dotenv_path='env')
    client_id = os.getenv('CLIENT_ID')
    client_secret = os.getenv('CLIENT_SECRET')
    headers = {
        'X-Naver-Client-Id': client_id,
        'X-Naver-Client-Secret':client_secret
    }
    query = quote(query)
    url = f'https://openapi.naver.com/v1/search/image?query={query}&display=100'
    request = Request(url, headers=headers)
    response = urlopen(request)
    items = json.loads(response.read())['items']
    
    items_list = []
    for idx, item in enumerate(items):
        link = item.get('link')
        thumbnail = item.get('thumbnail'),
        items_list.append({
            '제목':item.get('title'),
            '링크':link,
            '썸네일':item.get('thumbnail'),
            'sizeheight':item.get('sizeheight'),
            'sizewidth':item.get('sizewidth')
        })
    
        #이미지 저장 save_image('메인',idx, link, query) save_image('썸네일',idx, thumblink, query)
        save_image('메인',idx,link, query )
        save_image('썸네일',idx,link, query )
        if idx%10==0:
            print(f'==={idx}% 진행완료 ===')
    result = pd.DataFrame(items_list)
    result.to_csv('image/img_list.csv',encoding='utf-8',index=False)
    print('이미지 및 csv 저장완료')
    return result

In [46]:
get_image_list_save_file('프로야구')

===0% 진행완료 ===
===10% 진행완료 ===
13번째메인의 url에서 확장자를 추출 못하여 header에서 도전해봄
13번째썸네일의 url에서 확장자를 추출 못하여 header에서 도전해봄
===20% 진행완료 ===
25번째메인의 url에서 확장자를 추출 못하여 header에서 도전해봄
25번째썸네일의 url에서 확장자를 추출 못하여 header에서 도전해봄
27번째메인의 url에서 확장자를 추출 못하여 header에서 도전해봄
27번째썸네일의 url에서 확장자를 추출 못하여 header에서 도전해봄
===30% 진행완료 ===
===40% 진행완료 ===
41번째메인의 url에서 확장자를 추출 못하여 header에서 도전해봄
41번째썸네일의 url에서 확장자를 추출 못하여 header에서 도전해봄
46번째메인의 url에서 확장자를 추출 못하여 header에서 도전해봄
46번째썸네일의 url에서 확장자를 추출 못하여 header에서 도전해봄
===50% 진행완료 ===
55번째메인의 url에서 확장자를 추출 못하여 header에서 도전해봄
55번째썸네일의 url에서 확장자를 추출 못하여 header에서 도전해봄
===60% 진행완료 ===
67번째메인의 url에서 확장자를 추출 못하여 header에서 도전해봄
67번째썸네일의 url에서 확장자를 추출 못하여 header에서 도전해봄
===70% 진행완료 ===
===80% 진행완료 ===
===90% 진행완료 ===
이미지 및 csv 저장완료

,제목,링크,썸네일,sizeheight,sizewidth
0,"프로야구 1000만 관중 시대…정말 20, 30대 여성 덕일까 : kini's Sp...",https://blog.kakaocdn.net/dna/bpCkSI/btsJVKGrs...,https://search.pstatic.net/sunny/?type=b150&sr...,467,700
1,2015 프로야구 9월 25일 경기 일정 [인포그래픽],http://imgnews.naver.net/image/5369/2015/09/25...,https://search.pstatic.net/common/?type=b150&s...,1140,540
2,[KBO] 오늘자 8/19 프로야구 경기 결과 및 순위 - 스퀘어 카테고리,https://img.theqoo.net/img/tzhgi.jpg,https://search.pstatic.net/sunny/?type=b150&sr...,861,1080
3,프로야구 본격 개막[스경포토],http://imgnews.naver.net/image/144/2022/04/03/...,https://search.pstatic.net/common/?type=b150&s...,400,600
4,"컴투스프로야구V22, V23으로…'타점 배틀' 등 추가",http://imgnews.naver.net/image/5366/2023/01/18...,https://search.pstatic.net/common/?type=b150&s...,516,600
...,...,...,...,...,...
95,실황 파워풀 프로야구 9 - 나무위키 실황 파워풀 프로야구 9,https://i.namu.wiki/i/t0ioOi7MUNf65UUih1cw5CqZ...,https://search.pstatic.net/sunny/?type=b150&sr...,500,350
96,"2017 프로야구 시범경기, 오늘부터 시작…총 60경기 치뤄",http://imgnews.naver.net/image/123/2017/03/14/...,https://search.pstatic.net/common/?type=b150&s...,323,520
97,프로야구생존기 - 나무위키 프로야구생존기,https://i.namu.wiki/i/nFYAa3x4w_havUGBKlgfFguS...,https://search.pstatic.net/sunny/?type=b150&sr...,402,299
98,프로야구 인기 심상찮다…시범경기 첫 주말 관중 '13.8만명' 역대 최다,http://imgnews.naver.net/image/008/2025/03/09/...,https://search.pstatic.net/common/?type=b150&s...,590,1024
99,"컴투스, 컴투스프로야구V22 정식 출시",http://imgnews.naver.net/image/5017/2022/04/05...,https://search.pstatic.net/common/?type=b150&s...,281,500

### 2.3 XML웹데이터 수집
- RSS서비스, openAPI사용 
### 1) 전국 날씨 RSS를 BeautifulSoup을 이용한 xml크롤링
- 기상청 RSS에서 1개월 기상정보를 서비스

In [56]:
##방법1
import requests
from bs4 import BeautifulSoup
import pandas as pd ##Dataframe 
import numpy as np  ##astype으로 숫자형 문자를 숫자로 변환
items_list =[]
url ='https://www.kma.go.kr/repositary/xml/fct/mon/img/fct_mon1rss_108_20260813.xml'
target=requests.get(url)
#target RSS는 당연히 200
soup = BeautifulSoup(target.text,'xml')
locals = soup.select('local_ta')
#print(locals[0])
for local in locals:
    local_name = local.select_one('local_ta_name').text.strip()
    week1_local_ta_normalYear = local.select_one('week1_local_ta_normalYear').text #평년기온
    week1_local_ta_similarRange = local.select_one('week1_local_ta_similarRange').text
    week1_local_ta_minVal = local.select_one('week1_local_ta_minVal').text# 평년보다 낮을 확률
    week1_local_ta_similarVal = local.select_one('week1_local_ta_similarVal').text# 비슷할 확률
    week1_local_ta_maxVal = local.select_one('week1_local_ta_maxVal').text #평년보다 높을 확률
    items_list.append({
        '지역':local_name,
        '평년기온' :week1_local_ta_normalYear,
        '예측범위' :week1_local_ta_similarRange,
        '낮을확률' :week1_local_ta_minVal,
        '같을확률' :week1_local_ta_similarVal, 
        '높을확률' :week1_local_ta_maxVal,
    })
df=pd.DataFrame(items_list)
df.head()

             지역  평년기온       예측범위 낮을확률 같을확률 높을확률
0  전국(제주도,북한제외)  23.7  23.1~24.3   10   30   60
1     서울ㆍ인천ㆍ경기도  23.9  23.3~24.5   10   30   60
2        강원도 영서  22.1  21.4~22.8   10   30   60
3        강원도 영동  22.0  21.3~22.7   10   30   60
4    대전ㆍ세종ㆍ충청남도  24.0  23.4~24.6   10   30   60

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   지역      13 non-null     object
 1   평년기온    13 non-null     object
 2   예측범위    13 non-null     object
 3   낮을확률    13 non-null     object
 4   같을확률    13 non-null     object
 5   높을확률    13 non-null     object
dtypes: object(6)
memory usage: 752.0+ bytes

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   지역      13 non-null     object
 1   평년기온    13 non-null     object
 2   예측범위    13 non-null     object
 3   낮을확률    13 non-null     object
 4   같을확률    13 non-null     object
 5   높을확률    13 non-null     object
dtypes: object(6)
memory usage: 752.0+ bytes

In [59]:
##숫자로 바꾸기
df['평년기온']=df['평년기온'].astype(np.float64)

In [62]:
df['낮을확률']=df['낮을확률'].astype(np.int16)
df['같을확률']=df['같을확률'].astype(np.int16)
df['높을확률']=df['높을확률'].astype('int16')

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   지역      13 non-null     object
 1   평년기온    13 non-null     float64
 2   예측범위    13 non-null     object
 3   낮을확률    13 non-null     int16
 4   같을확률    13 non-null     int16
 5   높을확률    13 non-null     int16
dtypes: float64(1), int16(3), object(2)
memory usage: 518.0+ bytes

In [64]:
df

              지역  평년기온       예측범위  낮을확률  같을확률  높을확률
0   전국(제주도,북한제외)  23.7  23.1~24.3    10    30    60
1      서울ㆍ인천ㆍ경기도  23.9  23.3~24.5    10    30    60
2         강원도 영서  22.1  21.4~22.8    10    30    60
3         강원도 영동  22.0  21.3~22.7    10    30    60
4     대전ㆍ세종ㆍ충청남도  24.0  23.4~24.6    10    30    60
5           충청북도  23.2  22.6~23.8    10    30    60
6        광주ㆍ전라남도  24.9  24.3~25.5    10    30    60
7          전북자치도  23.9  23.3~24.5    10    30    60
8     부산ㆍ울산ㆍ경상남도  24.6  24.0~25.2    10    30    60
9        대구ㆍ경상북도  23.4  22.8~24.0    10    30    60
10           제주도  26.0  25.4~26.6    10    30    60
11     평안남북도ㆍ황해도  22.7  22.1~23.3    10    30    60
12         함경남북도  19.9  19.3~20.5    10    30    60

### 2) xml로 응답하는 open API 활용
 - dat.go.kr에서
   * 서울특별시_노선정보조회 서비스(버스id, 버스 정류장 목록-정류장id와 정류장이름)
   * 서울특별시_버스위치정보조회 서비스(실시간 버스 위치 목록)

In [ ]:
#step 1: 버스번호의 busRouteId 받아오기
#서울특별시_노선정보조회 서비스 : 노선번호 목록 조회(3번. getBusRouteList)
# http://api.bus.go.kr/contents/sub02/getBusRouteList.html

In [67]:
# 인증키
from dotenv import load_dotenv
import os
load_dotenv()
Key=os.getenv('key')

In [83]:
import requests
from urllib.request import quote
from bs4 import BeautifulSoup
from urllib.request import urlretrieve # xml을 로컬에 저장
# busNum =quote('마포01') 한글이 포함된 사항은 quote
busNum ='162'
key= os.getenv('key')
url1=f'http://ws.bus.go.kr/api/rest/busRouteInfo/getBusRouteList?ServiceKey={key}&strSrch={quote(busNum)}'
print(url)
# savefilename1='data/ch14_1.busInfo.xml'
# urlretrieve(url1, savefilename1)
# with open(savefilename1, encoding='utf-8') as f:
#     xml =f.read()
# soup=BeautifulSoup(xml,'xml')
xml = requests.get(url1)
soup=BeautifulSoup(xml.text,'xml')

http://ws.bus.go.kr/api/rest/busRouteInfo/getBusRouteList?ServiceKey=6ac28314737f0b0552125ddc4c426218f3b240cc8c4c7a3f0c8983d1c71f5f49&strSrch=162

In [84]:
#items_list=[]
for item in soup.select('itemList'):
    busRouteNm = item.find('busRouteNm').text
    if busNum == busRouteNm :
        busRouteId = item.find('busRouteId').text
        break
print('busRouteId = ', busRouteId)

busRouteId =  100100034

In [ ]:
#step 2: 해당 busRouteId의 정류장 목록 받아오기(정류장id, 정류장이름)
#서울특별시_노선정보조회 서비스 : 노선번호 목록 조회(4번. getStaionsByRouteList)
# http://api.bus.go.kr/contents/sub02/getStaionByRoute.html

In [126]:
import pandas as pd
url2=f'http://ws.bus.go.kr/api/rest/busRouteInfo/getStaionByRoute?ServiceKey={key}&busRouteId={busRouteId}'
response =requests.get(url2)
soup = BeautifulSoup(response.text,'xml')
itemLists=soup.select('itemList')
print(f'{busNum}번 정류장 갯수:', len(itemLists))
bus_station=[]
for itemList in itemLists:
    stationNm = itemList.select_one('stationNm').text #정류장명
    station = itemList.select_one('station').text #정류장ID
    gpsX     = itemList.select_one('gpsX').text# 경도
    gpsY     = itemList.select_one('gpsY').text# 경도 
    bus_station.append([stationNm, station, gpsX, gpsY])
df_station=pd.DataFrame(bus_station, columns=['정류소명','ID','경도','위도'])
df_station.head()

162번 정류장 갯수: 77

             정류소명         ID              경도             위도
0         정릉산장아파트  107000071      127.003343      37.616712
1    정릉4동주민센터.경국사  107000073      127.006345      37.613529
2     북한산보국문역2번출구  107000518  127.0079858233   37.612293899
3  성북청수도서관.정릉4동성당  107000075  127.0084193769  37.6115696748
4          정릉시장입구  107000077  127.0098212542  37.6084653256

In [99]:
pd.options.display.max_rows=100

In [ ]:
#step 3: 해당 busRouteId의 차량들의 위치정보(차량번호, 혼잡도, 경도, 위도, 최종정류장id, 다음정류장id, 도착소요시간)
#서울특별시_버스위치정보조회 서비스 : 노선번호 목록 조회(2번. getBusPosByRtidList)
# http://ws.bus.go.kr/api/rest/buspos/getBusPosByRtid

In [229]:
url3=f'http://ws.bus.go.kr/api/rest/buspos/getBusPosByRtid?ServiceKey={key}&busRouteId={busRouteId}'
print(url3)
response = requests.get(url3)
soup = BeautifulSoup(response.text,'xml')
itemLists=soup.select('itemList')
print(f'{busNum}번 운행중인 버스는 {len(itemLists)}대 입니다')
bus_position=[]
for itemList in itemLists:
    plainNo=itemList.select_one('plainNo').text
    congetion=itemList.select_one('congetion').text
    #혼잡도(0 : 없음, 3 : 여유, 4 : 보통, 5 : 혼잡)
    congetion = '없음' if congetion=='0' \
            else '여유' if congetion=='3'\
            else '보통' if congetion=='4'\
            else '혼잡'
    gpsX=itemList.select_one('gpsX').text
    gpsY=itemList.select_one('gpsY').text
    lastStnId=itemList.select_one('lastStnId').text
    nextStId=itemList.select_one('nextStId').text
    nextStTm=itemList.select_one('nextStTm').text
    bus_position.append([plainNo, congetion, gpsX, gpsY,lastStnId,nextStId,nextStTm])
df_position=pd.DataFrame(bus_position, columns=['차량번호','혼잡도','경도','위도','최종정류소id','다음정류소id','도착시간소요'])
df_position.head()

http://ws.bus.go.kr/api/rest/buspos/getBusPosByRtid?ServiceKey=6ac28314737f0b0552125ddc4c426218f3b240cc8c4c7a3f0c8983d1c71f5f49&busRouteId=100100034
162번 운행중인 버스는 23대 입니다

        차량번호 혼잡도          경도         위도    최종정류소id    다음정류소id 도착시간소요
0  서울70사6557  없음  127.000622  37.617561  107000071  107000169    381
1  서울74사3372  여유  127.013509  37.602426  107000168  101000042   2311
2  서울74사1604  여유  127.006711  37.588787  107000009  101000042   1797
3  서울74사3366  여유  126.991733  37.577647  100000002  101000042   1410
4  서울70사6549  여유  126.983335  37.575667  100000369  101000042    878

In [135]:
df_station.loc[df_station['ID']=='107000168','정류소명'].iloc[0]

'정릉입구.정릉역'

In [230]:
def get_station_name(row):
    row['최종정류소명']=df_station.loc[df_station['ID']==row['최종정류소id'],'정류소명'].iloc[0]
    row['다음정류소명']=df_station.loc[df_station['ID']==row['다음정류소id'],'정류소명'].iloc[0]
    return row

In [231]:
#get_station_name(df_position.iloc[0])
df_position= df_position.apply(get_station_name,axis=1)

In [232]:
drop_col=df_position.columns.str.contains('id')
drop_columns_names=df_position.columns[drop_col]
df_position.drop(drop_columns_names,axis=1,inplace=True)

In [233]:
df_position['도착시간소요']=round(df_position['도착시간소요'].astype(int)/60,2)
df_position.head()

        차량번호 혼잡도          경도         위도  도착시간소요       최종정류소명      다음정류소명
0  서울70사6557  없음  127.000622  37.617561    6.35      정릉산장아파트    정릉입구.정릉역
1  서울74사3372  여유  127.013509  37.602426   38.52     정릉입구.정릉역  소공동.롯데영플라자
2  서울74사1604  여유  127.006711  37.588787   29.95    삼선교.한성대학교  소공동.롯데영플라자
3  서울74사3366  여유  126.991733  37.577647   23.50  창경궁.서울대학교병원  소공동.롯데영플라자
4  서울70사6549  여유  126.983335  37.575667   14.63  안국역.서울공예박물관  소공동.롯데영플라자

# 3절. 연습문제
 - YES24 베스트셀러 정보에서 순위1~48위까지의 "순위, 책이름, 저자, 출판사, 가격정보를 출력하고
 - ch14_yest24_bestseller.csv로 백업

In [238]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

data=[]
for page in range(1,3):
    url=f'https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageSize=24&pageNumber={page}'
    response = requests.get(url)
    soup =BeautifulSoup(response.text,'html.parser')
    title_els=soup.select('div.info_row.info_name > a.gd_name')
    author_els=soup.select('span.authPub.info_auth > a:first-child')
    company_els=soup.select('span.authPub.info_pub > a')
    price_els=soup.select('strong.txt_num > em.yes_b')

    for idx, (title, author, company, price) in enumerate(zip(title_els, author_els, company_els, price_els)):
        data.append({'순위':(page-1)*24+idx+1,
                    '책이름':title.text,      
                    '저자':author.text,
                    '출판사':company.text,
                    '가격':price.text +'원'
                    })
pd.DataFrame(data)
df=pd.DataFrame(data)
df.to_csv('data/ch14_yest24_bestseller.csv',encoding='utf-8',index=False)

TypeError: 'NoneType' object is not iterable

In [215]:
pd.DataFrame(data)

,순위,책이름,저자,출판사,가격
0,1,"세네카, 오늘을 빼앗기고 있는 당신에게",루키우스 안나이우스 세네카,논픽션,"16,200원"
1,2,오디세이아,호메로스,현대지성,"24,300원"
2,3,원소 원정대: 118개 캐릭터로 마스터하는 주기율표 공략집,아게도리도리,윌북주니어,"17,820원"
3,4,오뒷세이아,호메로스,을유문화사,"22,500원"
4,5,싯다르타,헤르만 헤세,민음사,"7,200원"
5,6,투명한 나선,히가시노 게이고,북다,"19,800원"
6,7,니체의 초월자,프리드리히 니체,히읏,"15,210원"
7,8,오디세이아,호메로스,마음이음,"15,120원"
8,9,모순,양귀자,쓰다,"11,700원"
9,10,최상위권의 비밀,김민지,동양북스(동양books),"17,820원"
10,11,그랬다고 적었다,김애란,문학동네,"15,300원"
11,12,테오,앨런 레비,오팬하우스,"18,900원"
12,13,일리아스,호메로스,마음이음,"15,120원"
13,14,독서의 기술,고명환,라곰,"17,820원"
14,15,공부가 결국 너를 지켜줄 거야,임민찬,퍼스트펭귄,"17,820원"
15,16,"2026 큰별쌤 최태성의 별별한국사 한국사능력검정시험 심화(1,2,3급) 상",최태성,이투스북,"17,100원"
16,17,ETS 토익 정기시험 기출문제집 1000 Vol. 5 RC,ETS,YBM(와이비엠),"19,800원"
17,18,수족관,유래혁,포스터샵,"15,930원"
18,19,일리아스&오디세이아 세트,호메로스,현대지성,"49,500원"
19,20,ETS 토익 정기시험 기출문제집 1000 Vol. 5 LC,ETS,YBM(와이비엠),"19,800원"
20,21,내면 근력,짐 머피,윌북(willbook),"19,800원"
21,22,나는 왜 네 말이 힘들까,박재연,한빛라이프,"19,800원"
22,23,2027 공단기 소방단기 써니 행정법총론 기본서,박준철,공단기(에스티유니타스),"39,600원"
23,24,"돈, 뜨겁게 사랑하고 차갑게 다루어라",앙드레 코스톨라니,미래의창,"13,500원"
24,25,"2026 큰별쌤 최태성의 별별한국사 한국사능력검정시험 심화(1,2,3급) 하",최태성,이투스북,"16,650원"
25,26,안녕이라 그랬어 (집 에디션),김애란,문학동네,"15,120원"
26,27,2027 유휘운 행정법총론 요약노트+기출문제 (요.플.),유휘운,모두공북스,"33,300원"
27,28,급류,정대건,민음사,"12,600원"
28,29,프로젝트 헤일메리,앤디 위어,알에이치코리아(RHK),"19,800원"
29,30,나의 첫 번째 부동산 교과서,송희구,서삼독,"20,700원"
30,31,"안녕, 피터팬",전경철,이야기장수,"19,800원"
31,32,2027 공단기 소방단기 써니 행정법총론 핵심집약,박준철,공단기(에스티유니타스),"30,600원"
32,33,데미안,헤르만 헤세,민음사,"7,200원"
33,34,용의자 X의 헌신,히가시노 게이고,재인,"16,920원"
34,35,독하게 돈 공부,박소연,메이븐,"20,700원"
35,36,절창 切創,구병모,문학동네,"16,200원"
36,37,2027 이동기 영어 문법 500제 + 핵심문법 44포인트 요약노트,(주)이앤미래(이동기),지금(도서출판),"24,300원"
37,38,너는 원래 괜찮은 사람이야,윤지영,터닝페이지,"17,100원"
38,39,수험생을 위한 100일 기도,김종국,생활성서사,"14,400원"
39,40,엄마를 만나러 가는 길 : 사랑스러운 동그라미,고먕,다산어린이,"13,500원"
40,41,타몬 군 지금 어느 쪽?! 13 한정판,시와스 유키,학산문화사,"12,600원"
41,42,행복할 거야 이래도 되나 싶을 정도로,일홍,부크럼,"16,200원"
42,43,빵충 사육 준수 사항,김혜영,안전가옥,"15,120원"
43,44,브람스를 좋아하세요...,프랑수아즈 사강,민음사,"9,000원"
44,45,괴테는 모든 것을 말했다 (여름 에디션),스즈키 유이,리프,"15,300원"
45,46,만화로 보는 5분 한국사,유요,빅피시,"16,920원"
46,47,문해내공,신종호,상상스퀘어,"22,500원"
47,48,"2026 큰별쌤 최태성의 별별한국사 기출 500제 한국사능력검정시험 심화(1,2,3급)",최태성,이투스북,"19,800원"