In [4]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:90% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:20pt;}
.inner_cell{font-size:20pt;}
div.text_cell_render pre code {font-size:20pt; line-height:30px;}
div.output {font-size:20pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:10pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:20pt;padding:5px;}
table.dataframe{font-size:20px;}
</style>
"""))

<font color ='red' size='6'><b>ch14. 웹 데이터 수집</b></font>

# 1절. BeautifulSoup과 parser
    (정적 웹크롤링, 공공api사용)
`pip install bs4` 아나콘다를 설치하면 자동 설치되는 패키지에 포함
- 공식사이트 : https://www.crummy.com/software/BeautifulSoup/
- Documentation : https://www.crummy.com/software/BeautifulSoup/bs4/doc/

In [6]:
import requests #HTTP요청 처리하는 lib
#file://ai/lecNote/
#http://www.
from requests_file import FileAdapter

In [10]:
#로컬에 있는 파일을 웹요청하듯이 읽어오는 작업
s = requests.Session()
s.mount("file://",FileAdapter()) #file://로 시작하는 url을 어댑터가 처리
response=s.get("file:///ai/lecNote/01_python/data/ch14_sample.html") #c:/ai/lecNote/data/ch14_sample.html
response  #html편지봉투   /  편지지 header

In [11]:
# %ls "c:/ai/lecNote/01_python/data/ch14_sample.html"

In [12]:
if response:
    print('해당 url에 접근함')
else:
    print('해당 url에 거부됨')

해당 url에 접근함

In [ ]:
response.status_code
#200:정상
#404:없는페이지

In [13]:
response.content #html의 바이너리 형식의 내용

b'<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n  <meta charset="UTF-8">\r\n</head>\r\n<body>\r\n  <h1 class="greeting css" id="text">Hello, CSS</h1>\r\n  <h1 class="css">Hi, CSS</h1>\r\n  <div id="subject">subject \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90 \xec\x95\x88\xec\x9d\x98 \xeb\x82\xb4\xec\x9a\xa9</div>\r\n  <p>CSS \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\x8a\x94 \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xea\xb3\xb3\xec\x97\x90\xec\x84\x9c \xed\x99\x9c\xec\x9a\xa9\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4</p>\r\n  <div class="contents">\r\n    \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\xa5\xbc \xec\x96\xb4\xeb\x96\xbb\xea\xb2\x8c \xec\x9e\x91\xec\x84\xb1\xed\x95\x98\xeb\x8a\x90\xeb\x83\x90\xec\x97\x90 \xeb\x94\xb0\xeb\x9d\xbc\r\n    <span>\xeb\x8b\xa4\xeb\xa5\xb8<b>\xec\x9a\x94\xec\x86\x8c\xea\xb0\x80 \xeb\xb0\x98\xed\x99\x98</b></span>\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4\r\n  </div>\r\n  <div>CSS \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\x8a\x94 \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xea\xb3\xb3\xec\x97\x90 <b>\xed\x99\x9c\xec\x9a\xa9</b>\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4</div>\r\n</body>\r\n</html>'

In [14]:
print(response.content.decode('utf-8'))

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
</head>
<body>
  <h1 class="greeting css" id="text">Hello, CSS</h1>
  <h1 class="css">Hi, CSS</h1>
  <div id="subject">subject 선택자 안의 내용</div>
  <p>CSS 선택자는 다양한 곳에서 활용됩니다</p>
  <div class="contents">
    선택자를 어떻게 작성하느냐에 따라
    <span>다른<b>요소가 반환</b></span>됩니다
  </div>
  <div>CSS 선택자는 다양한 곳에 <b>활용</b>됩니다</div>
</body>
</html>

In [16]:
response.text

'<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n  <meta charset="UTF-8">\r\n</head>\r\n<body>\r\n  <h1 class="greeting css" id="text">Hello, CSS</h1>\r\n  <h1 class="css">Hi, CSS</h1>\r\n  <div id="subject">subject 선택자 안의 내용</div>\r\n  <p>CSS 선택자는 다양한 곳에서 활용됩니다</p>\r\n  <div class="contents">\r\n    선택자를 어떻게 작성하느냐에 따라\r\n    <span>다른<b>요소가 반환</b></span>됩니다\r\n  </div>\r\n  <div>CSS 선택자는 다양한 곳에 <b>활용</b>됩니다</div>\r\n</body>\r\n</html>'

In [15]:
print(response.text)

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
</head>
<body>
  <h1 class="greeting css" id="text">Hello, CSS</h1>
  <h1 class="css">Hi, CSS</h1>
  <div id="subject">subject 선택자 안의 내용</div>
  <p>CSS 선택자는 다양한 곳에서 활용됩니다</p>
  <div class="contents">
    선택자를 어떻게 작성하느냐에 따라
    <span>다른<b>요소가 반환</b></span>됩니다
  </div>
  <div>CSS 선택자는 다양한 곳에 <b>활용</b>됩니다</div>
</body>
</html>

In [19]:
#html 파싱 객체
from bs4 import BeautifulSoup
soup = BeautifulSoup(response.text, 
                    "html.parser")
#soup

## 1.soup.select_one

In [36]:
#1. soup.select_one('선택자') : 해당 선택자 처음 하나 엘리먼트만 (태그 전체를 가져옴 텍스트만 가져오는게 아님)
el = soup.select_one('h1.greeting.css')
print('el=',el)
print('el,text=>',el.text)
print('el,string=>',el.string)
print('el의 속성들 =>',el.attrs)
print('el의 class속성=>',el.attrs['class'])
print('el의 class속성=>',el.attrs.get('class'))
print('el의 href속성=>',el.attrs.get('href'))
#print('el의 href속성=>',el.attrs['href']) []로 불러낼때는 error 발생으로 get 함수 사용이 더 좋다
print('el의 name=>',el.name)

el= <h1 class="greeting css" id="text">Hello, CSS</h1>
el,text=> Hello, CSS
el,string=> Hello, CSS
el의 속성들 => {'class': ['greeting', 'css'], 'id': 'text'}
el의 class속성=> ['greeting', 'css']
el의 class속성=> ['greeting', 'css']
el의 href속성=> None
el의 name=> h1

## 2.soup.select

In [47]:
# 2.soup.select('선택자') : 해당 선택자 엘리먼트 다 list로
els = soup.select('h1.css')
print('els =>',els)
print('els들의 text',els[0].text)
print('els들의 text',[el.text for el in els])
print('els들의 string',[el.string for el in els])
print('els들의 속성들',[el.attrs for el in els])
print('els들의 class속성들',[el.attrs.get('class') for el in els])

els => [<h1 class="greeting css" id="text">Hello, CSS</h1>, <h1 class="css">Hi, CSS</h1>]
els들의 text Hello, CSS
els들의 text ['Hello, CSS', 'Hi, CSS']
els들의 string ['Hello, CSS', 'Hi, CSS']
els들의 속성들 [{'class': ['greeting', 'css'], 'id': 'text'}, {'class': ['css']}]
els들의 class속성들 [['greeting', 'css'], ['css']]

## 3.soup.find

In [57]:
# 3.soup.find('태그', 속성) vs soup.select_one('선택자') : 해당 속성을 갖은 태그 처음 하나만 
print('select_one:', soup.select_one('h1.css'))
print('find      :', soup.find('h1',{'class':'css'}))
# print('find      :', soup.find('h1',{'css'})) 왜 되는지 확인!
print('find      :', soup.find('h1',class_='css'))
print()
print('select_one:',soup.select_one('h1#text'))
print('select_one:',soup.find('h1',{'id':'text'}))

select_one: <h1 class="greeting css" id="text">Hello, CSS</h1>
find      : <h1 class="greeting css" id="text">Hello, CSS</h1>
find      : <h1 class="greeting css" id="text">Hello, CSS</h1>

select_one: <h1 class="greeting css" id="text">Hello, CSS</h1>
select_one: <h1 class="greeting css" id="text">Hello, CSS</h1>

## 4.soup.find_all

In [66]:
# 3.soup.find_all('태그', 속성) vs soup.select('선택자') : 해당 엘리먼트 다 list로
print('모든 h1.css 와 span태그 :', soup.select('h1.css, span'))
print('모든 h1.css 와 span태그 :', soup.find_all(['h1'],class_='css')+soup.find_all('span'))

모든 h1.css 와 span태그 : [<h1 class="greeting css" id="text">Hello, CSS</h1>, <h1 class="css">Hi, CSS</h1>, <span>다른<b>요소가 반환</b></span>]
모든 h1.css 와 span태그 : [<h1 class="greeting css" id="text">Hello, CSS</h1>, <h1 class="css">Hi, CSS</h1>, <span>다른<b>요소가 반환</b></span>]

In [77]:
#없는 Element 찾기
print('find_all(빈list) : ', soup.find_all('a'))
print('find(None)       : ', soup.find('a'))
print('select(빈list)   : ', soup.select('a'))
print('select_one(None) : ', soup.select_one('a'))

find_all(빈list) :  []
find(None)       :  None
select(빈list)   :  []
select_one(None) :  None

# 2절. 정적 웹데이터 수집(정적 웹크롤링)
## 2.1 BeautifulSoup 모듈을 활용한 html 웹데이터 수집
### 1) 환율정보 가져오기(네이버증권>시장지표)

 - https://finance.naver.com/marketindex/
 
     * 크롤링 허용범위는 사이트마다 ~/robots.txt에서 확인할 수 있음
         - Allow : 크롤링 허용 가능한 폴더
         - Disallow : 크롤링 제한 폴더
       ex )https://finance.naver.com/robots.txt 로 검색하면 
       User-agent: *
        Disallow: /
        User-agent: yeti
        Disallow: /
        Allow: /sise/
        Allow: /research/
        Allow: /marketindex/
        Allow: /fund/
        Allow: /template/head_js.naver
        Allow: /world/
        Allow: /item/board.naver?code=*
        Disallow: /item/board.naver?code=*&page=*
        Disallow : /fund/news/
        Disallow : /marketindex/news/

In [86]:
#soup 객체 생성 방법1
import requests
from bs4 import BeautifulSoup
url = 'https://finance.naver.com/marketindex/'
response = requests.get(url)
response # Response 객체
print(response.status_code)
#response.content
#print(response.text)   #이제 soup객체 만들수 있다
soup = BeautifulSoup(response.text,'html.parser')   # soup객체 만드는 방법 1

200

In [99]:
#soup 객체 생성 방법2
from urllib.request import urlopen
url = 'https://finance.naver.com/marketindex/'
response = urlopen(url)
#response # HTTPResponse
print(response.status)
#response.read().decode('cp949')
soup = BeautifulSoup(response,'html.parser')

200

In [114]:
p= '1,417.70'
float(p.replace(',','')) # ,없애는 방법1 replace
float(''.join(p.split(',')))# ,없애는 방법1 ,로 split 후 ''으로 다시join 후 float

1417.7

In [125]:
#div.head_info 밑의 span.value (find계열)
prices = []
headinfos = soup.find_all('div',class_='head_info')
for headinfo in headinfos:
#    print(headinfo)
    price=headinfo.find('span',class_='value')
    prices.append(float(''.join(price.text.split(','))))
print(prices)

[1417.7, 889.17, 1635.6, 210.09, 159.24, 1.1541, 1.3507, 99.71, 83.2, 1863.92, 4441.1, 200855.05]

In [126]:
#span.value(find계열)
price_els = soup.find_all('span', class_='value')
prices = [round(float(price.text.replace(',','')),1) for price in price_els]
print(prices)

[1417.7, 889.2, 1635.6, 210.1, 159.2, 1.2, 1.4, 99.7, 83.2, 1863.9, 4441.1, 200855.0]

In [138]:
#div.head_info 밑의 span.value
price_els =soup.select('div.head_info > span.value')
#price_els
title_els =soup.select('h3.h_lst > span.blind')
title_els

[<span class="blind">미국 USD</span>,
 <span class="blind">일본 JPY(100엔)</span>,
 <span class="blind">유럽연합 EUR</span>,
 <span class="blind">중국 CNY</span>,
 <span class="blind">달러/일본 엔</span>,
 <span class="blind">유로/달러</span>,
 <span class="blind">영국 파운드/달러</span>,
 <span class="blind">달러인덱스</span>,
 <span class="blind">WTI</span>,
 <span class="blind">휘발유</span>,
 <span class="blind">국제 금</span>,
 <span class="blind">국내 금</span>]

In [150]:
# 단위들 : div.head_info > span > span.blind
unit_els = soup.select('div.head_info > span > span.blind')
unit_els
units= [unit_el.string for unit_el in unit_els]
units.insert(7,'')  #insert로 달러인덱스 단위에 빈문자 추가 
units

['원', '원', '원', '원', '엔', '달러', '달러', '', '달러', '원', '달러', '원']

In [152]:
# 상승/하락 : div.head_info > span.blind
trend_els = soup.select('div.head_info > span.blind')
trends=[trend.string for trend in trend_els]
trends

['상승', '상승', '상승', '상승', '상승', '하락', '하락', '상승', '상승', '하락', '상승', '상승']

In [158]:
# for idx in range(len(title_els)):
#     print("{}  :   {}   {}   -{}".format(title_els[idx].text,
#                                 price_els[idx].text,
#                                 units[idx],
#                                 trends[idx]))
# 좋은 방법 아님!!

미국 USD  :   1,417.70   원   -상승
일본 JPY(100엔)  :   889.17   원   -상승
유럽연합 EUR  :   1,635.60   원   -상승
중국 CNY  :   210.09   원   -상승
달러/일본 엔  :   159.2400   엔   -상승
유로/달러  :   1.1541   달러   -하락
영국 파운드/달러  :   1.3507   달러   -하락
달러인덱스  :   99.7100      -상승
WTI  :   83.2   달러   -상승
휘발유  :   1863.92   원   -하락
국제 금  :   4441.1   달러   -상승
국내 금  :   200855.05   원   -상승

In [ ]:
for title, price, unit, trend in zip(title_els, price_els, units, trend_els):
    print("{}:{}{}-{}".format(title.text,price.text,unit,trend.text))
##이방법을 필히 기억할 것

In [175]:
import pandas as pd
import numpy as np
data=[]
for title, price, unit, trend in zip(title_els, price_els, units, trend_els):
    data.append({'title':title.text,'price':float(price.text.replace(',','')),'unit':unit,'trend':trend.text})
pd.DataFrame(data)#.to_csv('data/file.csv',index=False)

           title        price unit trend
0         미국 USD    1417.7000    원    상승
1   일본 JPY(100엔)     889.1700    원    상승
2       유럽연합 EUR    1635.6000    원    상승
3         중국 CNY     210.0900    원    상승
4        달러/일본 엔     159.2400    엔    상승
5          유로/달러       1.1541   달러    하락
6      영국 파운드/달러       1.3507   달러    하락
7          달러인덱스      99.7100         상승
8            WTI      83.2000   달러    상승
9            휘발유    1863.9200    원    하락
10          국제 금    4441.1000   달러    상승
11          국내 금  200855.0500    원    상승

In [171]:
#넘파이 판다스 부동산 분석시스템 복습할것

In [181]:
data=[]
for title, price, unit, trend in zip(title_els, price_els, units, trend_els):
    data.append([title.text,float(price.text.replace(',','')),unit,trend.text])
pd.DataFrame(data,columns=['title','price','unit','trend'])

           title        price unit trend
0         미국 USD    1417.7000    원    상승
1   일본 JPY(100엔)     889.1700    원    상승
2       유럽연합 EUR    1635.6000    원    상승
3         중국 CNY     210.0900    원    상승
4        달러/일본 엔     159.2400    엔    상승
5          유로/달러       1.1541   달러    하락
6      영국 파운드/달러       1.3507   달러    하락
7          달러인덱스      99.7100         상승
8            WTI      83.2000   달러    상승
9            휘발유    1863.9200    원    하락
10          국제 금    4441.1000   달러    상승
11          국내 금  200855.0500    원    상승

### 2) 이번주 로또 번호 출력
- 방법2에서 User-Agent를 추가하여 soup생성
- https://search.daum.net/search?w=tot&DA=YZR&t__nil_searchbox=btn&q=lotto (다음에서 lotto검색)
```
    1236회((2026.08.08 추첨)
    당첨번호 [12, 18, 21, 29, 34, 38]
    보너스 10
```

In [188]:
#방법1
import requests
from bs4 import BeautifulSoup
url = 'https://search.daum.net/search?w=tot&DA=YZR&t__nil_searchbox=btn&q=lotto'
response = requests.get(url)
print('response의 상태 : ',response.status_code) # 200값 나오는지 확인
soup = BeautifulSoup(response.text,'html.parser')
#soup --> 정상 출력으로 가능

response의 상태 :  200

In [202]:
#방법2
from urllib.request import urlopen, Request
url = 'https://search.daum.net/search?w=tot&DA=YZR&t__nil_searchbox=btn&q=lotto'
headers={'User-agent' : 
         'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36'}
request = Request(url, headers=headers)

response = urlopen(request)
print('response의 상태 ',response.status)
soup = BeautifulSoup(response,'html.parser')
#soup

response의 상태  200

In [ ]:
#     1236회((2026.08.08 추첨)
#     당첨번호 [12, 18, 21, 29, 34, 38]
#     보너스 10

In [235]:
times = soup.select_one('div.prize span.f_red').text
date = soup.select_one('div.prize > span.date').text
title1= soup.select_one('div.prize > strong').text[-4:]
lotto_numbers = soup.select('div.lottonum > span.ball:nth-last-child(n+3)')
title2= soup.select_one('div.lottonum span.screen_out').text
bonus_number=soup.select_one('div.lottonum > span.bg_ball1').text
print(times,date)
print(title1,[int(numbers.text) for numbers in lotto_numbers])
print(title2,bonus_number)

1236회 (2026.08.08 추첨)
당첨번호 [12, 18, 21, 29, 34, 38]
보너스 10

In [218]:
# lotto_numbers = soup.select('div.lottonum > span.ball')[:-2]
# lotto_numbers

[<span class="ball bg_ball2">12</span>,
 <span class="ball bg_ball2">18</span>,
 <span class="ball bg_ball3">21</span>,
 <span class="ball bg_ball3">29</span>,
 <span class="ball bg_ball4">34</span>,
 <span class="ball bg_ball4">38</span>]

In [250]:
##select 를 find로 변경해서 작성해봄

# times = soup.select_one('div.prize span.f_red').text
prize= soup.find('div',class_='prize')
times = prize.find('span',class_='f_red').text
times

# date = soup.select_one('div.prize > span.date').text
date = prize.find('span',class_='date').text
date

# title1= soup.select_one('div.prize > strong').text[-4:]
title1=prize.find('strong').text[-4:]
title1

# lotto_numbers = soup.select('div.lottonum > span.ball:nth-last-child(n+3)')
lottonum=soup.find('div',class_='lottonum')
lottonumbers=lottonum.find_all('span',class_='ball')[:-2]
lottonumbers

# title2= soup.select_one('div.lottonum span.screen_out').text
title2=lottonum.find('span', class_='screen_out').text
title2

# bonus_number=soup.select_one('div.lottonum > span.bg_ball1').text
bonus_number=lottonum.find('span',class_='bg_ball1').text
bonus_number

print(times,date)
print(title1,[int(numbers.text) for numbers in lotto_numbers])
print(title2,bonus_number)

1236회 (2026.08.08 추첨)
당첨번호 [12, 18, 21, 29, 34, 38]
보너스 10

### 3) 다음 뉴스 검색 리스트
```
no title href
0 타이틀1 http://~
1 타이틀2 http://~
2 타이틀3 http://~
```

In [258]:
#방법1
import requests
from bs4 import BeautifulSoup
word= '비트코인'
url = f'https://search.daum.net/search?w=news&q={word}'
#url = 'https://search.daum.net/search?w=news&q={}'.format(word)
print(url)
response = requests.get(url)
print(response.status_code)
soup =BeautifulSoup(response.text,'html.parser')

https://search.daum.net/search?w=news&q=비트코인
200

In [269]:
#방법2
from urllib.request import urlopen, Request
from urllib.parse import quote #ASCII 코드 처리해주는 라이브러리
#word='%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8' ##브라우저 창에서 복사 붙여넣기 하면 ASCII 코드로 변환됨
word=quote('비트코인')
url = f'https://search.daum.net/search?w=news&q={word}&p=1'
print(url)
headers={'User-agent' : 
         'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36'}
#request = Request(url, headers=headers)
request = Request(url)
request.add_header('User-agent',
                   'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36')
response = urlopen(request)
print(response.status)
soup=BeautifulSoup(response,'html.parser')
#soup

https://search.daum.net/search?w=news&q=%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8&p=1
200

In [292]:
items_find_list =[] # 검색한 결과를 담을 dict 리스트
items_el=soup.select('div.item-title > strong.tit-g.clamp-g > a')
for idx, item in enumerate(items_el):
    #print(idx,item)
    items_find_list.append({'no':idx,
                            'tile':item.text,
                            'link':item.attrs.get('href')})
import pandas as pd
pd.DataFrame(items_find_list).head(3)

,no,tile,link
0,0,9000만원 깨진 비트코인…美물가지수 앞두고 위험회피 심리↑,http://v.daum.net/v/20260812104759348
1,1,[코인뉴스] 비트코인 박스권 지속…다음 변수는?,http://v.daum.net/v/20260812093050056
2,2,9000만원대 갇힌 비트코인…'100만弗 vs 4만弗' 극단 전망,http://v.daum.net/v/20260812161211645

In [298]:
items_find_list =[] # 검색한 결과를 담을 2차원 리스트
items_el=soup.select('div.item-title > strong.tit-g.clamp-g > a')
for idx, item in enumerate(items_el):
    items_find_list.append([idx,item.text,item.attrs.get('href')])
pd.DataFrame(items_find_list,columns=['순번','제목','링크'])

,순번,제목,링크
0,0,9000만원 깨진 비트코인…美물가지수 앞두고 위험회피 심리↑,http://v.daum.net/v/20260812104759348
1,1,[코인뉴스] 비트코인 박스권 지속…다음 변수는?,http://v.daum.net/v/20260812093050056
2,2,9000만원대 갇힌 비트코인…'100만弗 vs 4만弗' 극단 전망,http://v.daum.net/v/20260812161211645
3,3,[코인뉴스] CPI 앞둔 비트코인…박스권 속 엇갈린 베팅,http://v.daum.net/v/20260812163039451
4,4,[코인시세] 비트코인 6만3천달러대 약세…CPI 경계감 지속,http://v.daum.net/v/20260812103841887
5,5,"[08:03 가상자산] 비트코인, 美 CPI 결과 발표 앞두고 9000만원 선 붕괴",http://v.daum.net/v/20260812080815138
6,6,"트럼프 회사, 비트코인에 3300억 베팅했다 '쓴맛'⋯손실 12배 늘었다",http://v.daum.net/v/20260811144238992
7,7,"금리 공포 걷히자 ""금값 조정 끝났다""… 비트코인은 나 홀로 약세",http://v.daum.net/v/20260812164709172
8,8,[아주경제 코이너스 브리핑] 호르무즈 불확실성에…비트코인 6만3000달러대 횡보,http://v.daum.net/v/20260812082712570
9,9,비트코인 다시 6.3만달러대로…美 CPI 발표 ‘촉각’ [코인 모닝콜],http://v.daum.net/v/20260812082137419

In [300]:
#다음 뉴스 검색 함수(원하는 키워드, 원하는 페이지로)
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def collect_list(keyword, page):
    'keyword로 해당 page에 검색한 결과 dict list return'
    #url = f'https://search.daum.net/search?w=news&q={keyword}&p={page}'
    url= 'https://search.daum.net/search?w=news'
    params ={'q':keyword, 'p':page}
    response=request.get(url,params=params)
    soup = BeautifulSoup(response.text, 'html.parser')
    items_find_list=[]
    items_el=soup.select('div.item-title > strong.tit-g.clamp-g > a')
    for idx, item in enumerate(items_el):
        items_find_list.append({'no':(page-1)*10+idx,
                                'title':item.text,      
                                'link':item.attrs.get('href')})
    return items_find_list

In [301]:
collect_list('지구온난화',2)

AttributeError: 'Request' object has no attribute 'get'